using System.ComponentModel;

namespace MQTTMessageLib.Algorithm;

public enum AlgorithmRequestType
{
	[Description("关注点获取数据")]
	POI_GetData,
	[Description("畸变获取数据")]
	Distortion_GetData,
	[Description("SFR获取数据")]
	SFR_GetData,
	[Description("FOV获取数据")]
	FOV_GetData,
	[Description("MTF获取数据")]
	MTF_GetData,
	[Description("Ghost获取数据")]
	Ghost_GetData,
	[Description("灯珠检测")]
	LedCheck_GetData,
	[Description("发光区检测1")]
	LightArea_GetData,
	[Description("关注点生成")]
	BuildPOI,
	[Description("合规计算")]
	ComplianceMath,
	[Description("合规对比度")]
	Compliance_Contrast,
	[Description("合规判定")]
	Compliance_Judgment,
	[Description("灯带检测")]
	LEDStripDetection_GetData,
	[Description("实时关注点")]
	RealPOI_GetData,
	[Description("数据加载")]
	DataLoad_GetData,
	[Description("POI修正生成")]
	POIReviseGen_GetData,
	[Description("OLED灯珠检测2")]
	OLED_FindDotsArrayMem,
	[Description("OLED数据提取")]
	OLED_RebuildPixelsMem,
	[Description("OLED数据提取Pos")]
	OLED_RebuildPixelsPosMem,
	[Description("OLED定位及数据提取")]
	OLED_FindDotsArrayAndRebuildPixelsMem,
	[Description("JND")]
	OLED_JND_CalVas,
	[Description("发光区检测2")]
	LightArea2_GetData,
	[Description("发光区检测")]
	FindLightArea,
	[Description("OLED灯珠检测3")]
	OLED_FindLedPosition,
	[Description("OLED灯珠检测4")]
	OLED_FindDotsArrayByCornerPts,
	[Description("FindLed")]
	FindLed,
	[Description("OLED线缺陷")]
	OLED_FindVHLine,
	[Description("OLED点缺陷")]
	OLED_FindPixelDefectsForRebuildPicGrading,
	[Description("OLED点缺陷V2")]
	OLED_FindPixelDefectsForRebuildPicGradingV2,
	[Description("OLED点缺陷")]
	OLED_FindPixelDefectsForRebuildPic,
	[Description("OLED合并图片")]
	OLED_CombineQuaterImages,
	[Description("OLED亮点检测")]
	OLED_FindPixelDefectsForQuardImg,
	[Description("黑画面检测")]
	OLED_DetectBrightPixelsForBlackScreen,
	[Description("OLED Mura")]
	OLED_FindMura,
	[Description("OLED AOI ALL")]
	OLED_AOI_ALL,
	[Description("OLED灰尘检测及修补")]
	OLED_ParticlesFindAndFill,
	[Description("POI导入")]
	POI_CAD_Mapping,
	[Description("图像裁剪")]
	Image_Cropping,
	[Description("模板匹配")]
	MatchTemplate,
	[Description("KB获取数据")]
	KB_GetData,
	[Description("KB输出")]
	KB_Output,
	[Description("双目融合获取数据")]
	BinocularFusion_GetData,
	[Description("SFR ROI")]
	SFR_Find_ROI_GetData,
	[Description("BlackMura_Calc")]
	BlackMura_Calc_GetData,
	[Description("Math.DataConvert")]
	Math_DataConvert,
	[Description("ARVR_AAFindPoints")]
	ARVR_AAFindPoints,
	[Description("PoiAnalysis")]
	PoiAnalysis,
	[Description("FindCross")]
	FindCross,
	[Description("CompoundImg")]
	CompoundImg,
	[Description("CalcEQE")]
	CalcEQE,
	[Description("CaliAngleShift")]
	CaliAngleShift,
	[Description("VAMCutImage")]
	ImageROI,
	[Description("ImageConvert")]
	ImageConvert
}
