using System.Globalization;
using System.Resources;

namespace ColorVision.Settings.Maintenance;

public static class MaintenanceText
{
    private static readonly ResourceManager Manager = new("ColorVision.Settings.Maintenance.MaintenanceResources", typeof(MaintenanceText).Assembly);
    public static string Get(string key) => Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
    public static string Title => Get("Title");
    public static string Description => Get("Description");
    public static string Space => Get("Space");
    public static string Reclaimable => Get("Reclaimable");
    public static string Protected => Get("Protected");
    public static string Scan => Get("Scan");
    public static string CleanSelected => Get("CleanSelected");
    public static string Cancel => Get("Cancel");
    public static string Details => Get("Details");
    public static string Clean => Get("Clean");
    public static string NotScanned => Get("NotScanned");
    public static string ScanFirst => Get("ScanFirst");
    public static string Keep => Get("Keep");
    public static string Days => Get("Days");
    public static string Files => Get("Files");
    public static string Logs => Get("Logs");
    public static string LogsDescription => Get("LogsDescription");
    public static string Temporary => Get("Temporary");
    public static string TemporaryDescription => Get("TemporaryDescription");
    public static string Packages => Get("Packages");
    public static string PackagesDescription => Get("PackagesDescription");
    public static string Cie => Get("Cie");
    public static string CieDescription => Get("CieDescription");
    public static string Thumbnails => Get("Thumbnails");
    public static string ThumbnailsDescription => Get("ThumbnailsDescription");
    public static string Scanning => Get("Scanning");
    public static string Cleaning => Get("Cleaning");
    public static string ScanComplete => Get("ScanComplete");
    public static string Result => Get("Result");
    public static string Cancelled => Get("Cancelled");
    public static string ConfirmClean => Get("ConfirmClean");
    public static string History => Get("History");
    public static string Database => Get("Database");
    public static string DatabaseDescription => Get("DatabaseDescription");
    public static string Manage => Get("Manage");
    public static string Snapshots => Get("Snapshots");
    public static string SnapshotsDescription => Get("SnapshotsDescription");
    public static string ConfigBackup => Get("ConfigBackup");
    public static string ConfigBackupDescription => Get("ConfigBackupDescription");
    public static string CreateBackup => Get("CreateBackup");
    public static string OpenFolder => Get("OpenFolder");
    public static string Reset => Get("Reset");
    public static string ResetDescription => Get("ResetDescription");
    public static string Appearance => Get("Appearance");
    public static string Window => Get("Window");
    public static string Hotkeys => Get("Hotkeys");
    public static string Search => Get("Search");
    public static string Viewer => Get("Viewer");
    public static string ScheduleReset => Get("ScheduleReset");
    public static string CancelReset => Get("CancelReset");
    public static string ResetConfirm => Get("ResetConfirm");
    public static string ResetScheduled => Get("ResetScheduled");
    public static string ResetCancelled => Get("ResetCancelled");
    public static string BackupCreated => Get("BackupCreated");
    public static string AdminRequired => Get("AdminRequired");
    public static string SelectReset => Get("SelectReset");
    public static string FilePath => Get("FilePath");
    public static string Size => Get("Size");
    public static string Modified => Get("Modified");
    public static string Warnings => Get("Warnings");
    public static string ViewWarnings => Get("ViewWarnings");
    public static string NoFiles => Get("NoFiles");
    public static string Close => Get("Close");
    public static string BusyClose => Get("BusyClose");
    public static string ScanChanged => Get("ScanChanged");
    public static string Pending => Get("Pending");
    public static string CacheUnavailable => Get("CacheUnavailable");
    public static string Failed => Get("Failed");
    public static string ThumbnailList => Get("ThumbnailList");
    public static string StoppedForSafety => Get("StoppedForSafety");
}
