using ColorVision.UI.LogImp;
using ColorVision.UI.Menus;
using Spectrum.Menus;
using System.IO;
using System.Text;
using System.Windows;

namespace Spectrum.License
{
    /// <summary>
    /// Menu item to view the C++ spectrometer (cvCamera.dll) log file using WindowLogLocal.
    /// The log file is generated by the native library in the application directory.
    /// </summary>
    public class MenuSpectrometerNativeLog : SpectrumMenuIBase
    {
        public override string OwnerGuid => MenuItemConstants.Help;
        public override int Order => 10004;
        public override string Header => "光谱仪原生日志";

        public override void Execute()
        {
            // The C++ cvCamera.dll typically writes logs to the application's current directory
            string appDir = AppDomain.CurrentDomain.BaseDirectory;

            // Search for the most recent cvCamera/spectrometer log file
            string? logPath = FindSpectrometerLogFile(appDir);

            if (string.IsNullOrEmpty(logPath))
            {
                MessageBox.Show("未找到光谱仪原生日志文件", "日志", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            // Open with WindowLogLocal using GB2312 encoding (common for C++ logs in Chinese Windows)
            var window = new WindowLogLocal(logPath, Encoding.GetEncoding("GB2312"));
            window.Show();
        }

        /// <summary>
        /// Search for spectrometer-related log files in the application directory.
        /// </summary>
        private static string? FindSpectrometerLogFile(string baseDir)
        {
            if (!Directory.Exists(baseDir)) return null;

            // Check common log file patterns for cvCamera.dll
            string[] patterns = { "cvCamera*.log", "Spectr*.log", "Emission*.log", "*.log" };

            foreach (var pattern in patterns)
            {
                var files = Directory.GetFiles(baseDir, pattern, SearchOption.TopDirectoryOnly)
                    .OrderByDescending(f => new FileInfo(f).LastWriteTimeUtc)
                    .ToList();

                if (files.Count > 0)
                {
                    // For generic *.log pattern, filter to avoid picking up unrelated logs
                    if (pattern == "*.log")
                    {
                        var spectrometerLog = files.FirstOrDefault(f =>
                        {
                            string name = Path.GetFileName(f).ToLowerInvariant();
                            return name.Contains("camera") || name.Contains("spectr") || name.Contains("emission") || name.Contains("cvcamera");
                        });
                        if (spectrometerLog != null) return spectrometerLog;
                    }
                    else
                    {
                        return files[0];
                    }
                }
            }

            // Also check a "log" subdirectory
            string logDir = Path.Combine(baseDir, "log");
            if (Directory.Exists(logDir))
            {
                foreach (var pattern in patterns)
                {
                    var files = Directory.GetFiles(logDir, pattern, SearchOption.TopDirectoryOnly)
                        .OrderByDescending(f => new FileInfo(f).LastWriteTimeUtc)
                        .ToList();

                    if (files.Count > 0 && pattern != "*.log")
                    {
                        return files[0];
                    }
                }
            }

            return null;
        }
    }
}
