set(BUILD_CUDA_STUBS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_DOCS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_EXAMPLES "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_IPP_IW "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_ITT "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_JASPER "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_JAVA "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_JPEG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_OPENEXR "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_OPENJPEG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_PACKAGE "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_PERF_TESTS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_PNG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_PROTOBUF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_SHARED_LIBS "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_TBB "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_TESTS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_TIFF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_USE_SYMLINKS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_WEBP "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_WITH_DEBUG_INFO "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_WITH_DYNAMIC_IPP "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_WITH_STATIC_CRT "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_ZLIB "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_1394 "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ADE "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ARITH_DEC "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ARITH_ENC "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_AVIF "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_CANN "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_CLP "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_CUDA "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_DIRECTML "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_DIRECTX "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_DSHOW "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_EIGEN "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_FFMPEG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_FLATBUFFERS "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_FREETYPE "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_GDAL "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_GDCM "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_GSTREAMER "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_HALIDE "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_HPX "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IMGCODEC_GIF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IMGCODEC_HDR "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IMGCODEC_PFM "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IMGCODEC_PXM "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IMGCODEC_SUNRASTER "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_IPP "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ITT "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_JASPER "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_JPEG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_JPEGXL "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_LAPACK "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_LIBREALSENSE "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_MATLAB "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_MFX "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_MSMF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_MSMF_DXVA "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OAK "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OBSENSOR "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ONNX "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENCL "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENCLAMDBLAS "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENCLAMDFFT "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENCL_D3D11_NV "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENCL_SVM "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENEXR "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENGL "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENJPEG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENMP "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENNI "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENNI2 "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENVINO "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_OPENVX "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_PLAIDML "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_PNG "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_PROTOBUF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_PVAPI "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_QT "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_QUIRC "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_SPNG "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_TBB "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_TESSERACT "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_TIFF "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_TIMVX "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_UEYE "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_VTK "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_VULKAN "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_WEBNN "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_WEBP "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_WIN32UI "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_XIMEA "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(WITH_ZLIB_NG "OFF" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(CPU_BASELINE "SSE3" CACHE STRING "Inherited from OpenCV 4.14 build" FORCE)
set(CPU_DISPATCH "SSE4_1;SSE4_2;AVX;FP16;AVX2;AVX512_SKX;AVX512_ICL" CACHE STRING "Inherited from OpenCV 4.14 build" FORCE)
set(OPENCV_ENABLE_NONFREE "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(OPENCV_DNN_OPENCL "ON" CACHE BOOL "Inherited from OpenCV 4.14 build" FORCE)
set(OPENCV_MSVC_PARALLEL "2" CACHE STRING "Inherited from OpenCV 4.14 build" FORCE)
set(BUILD_opencv_apps OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_java OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_js OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_python3 OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_python_bindings_generator OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_java_bindings_generator OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_js_bindings_generator OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_objc_bindings_generator OFF CACHE BOOL "Native library distribution" FORCE)
set(BUILD_opencv_world OFF CACHE BOOL "Native library distribution" FORCE)
set(CMAKE_CXX_STANDARD 17 CACHE STRING "OpenCV 5 minimum C++ version" FORCE)


set(ENABLE_PRECOMPILED_HEADERS OFF CACHE BOOL "Avoid compiler PCH failures" FORCE)
set(ENABLE_CONFIG_VERIFICATION ON CACHE BOOL "Verify required backends" FORCE)

set(ENABLE_FAST_MATH OFF CACHE BOOL "Preserve numerical behavior" FORCE)
set(ENABLE_LTO OFF CACHE BOOL "Match existing build" FORCE)
