//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自动调整列宽 的本地化字符串。
        /// </summary>
        public static string AutoAdjustColumnWidth {
            get {
                return ResourceManager.GetString("AutoAdjustColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 的本地化字符串。
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动滚动到底部 的本地化字符串。
        /// </summary>
        public static string AutoScrollToEnd {
            get {
                return ResourceManager.GetString("AutoScrollToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动切换选中视图 的本地化字符串。
        /// </summary>
        public static string AutoSwitchSelectedView {
            get {
                return ResourceManager.GetString("AutoSwitchSelectedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前速度： 的本地化字符串。
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器支持正则 的本地化字符串。
        /// </summary>
        public static string FilterSupportsRegex {
            get {
                return ResourceManager.GetString("FilterSupportsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局 的本地化字符串。
        /// </summary>
        public static string GlobalMode {
            get {
                return ResourceManager.GetString("GlobalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲突 的本地化字符串。
        /// </summary>
        public static string HotkeyConflict {
            get {
                return ResourceManager.GetString("HotkeyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string HotkeyNormal {
            get {
                return ResourceManager.GetString("HotkeyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeys {
            get {
                return ResourceManager.GetString("HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键盘设置快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeySet1 {
            get {
                return ResourceManager.GetString("HotKeySet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击设置快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeySet2 {
            get {
                return ResourceManager.GetString("HotKeySet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动选择 的本地化字符串。
        /// </summary>
        public static string IsAutoSelect {
            get {
                return ResourceManager.GetString("IsAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        public static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩语 的本地化字符串。
        /// </summary>
        public static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户界面语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您必须重新启动才能使用新的语言设置 的本地化字符串。
        /// </summary>
        public static string LanguageResartSign {
            get {
                return ResourceManager.GetString("LanguageResartSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志级别 的本地化字符串。
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(_C) 的本地化字符串。
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(_C) 的本地化字符串。
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(_T) 的本地化字符串。
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(_D) 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(_E) 的本地化字符串。
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(_X) 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(_F) 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言(_L) 的本地化字符串。
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建(_N) 的本地化字符串。
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做(_R) 的本地化字符串。
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名(_M) 的本地化字符串。
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板(_M) 的本地化字符串。
        /// </summary>
        public static string MenuTemplate {
            get {
                return ResourceManager.GetString("MenuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具(_T) 的本地化字符串。
        /// </summary>
        public static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销(_U) 的本地化字符串。
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图(_V) 的本地化字符串。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置文件 的本地化字符串。
        /// </summary>
        public static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置文件夹 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolder {
            get {
                return ResourceManager.GetString("OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志文件夹 的本地化字符串。
        /// </summary>
        public static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓冲区大小 的本地化字符串。
        /// </summary>
        public static string SocketBufferSize {
            get {
                return ResourceManager.GetString("SocketBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间： 的本地化字符串。
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string UseSystem {
            get {
                return ResourceManager.GetString("UseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string WindowHidden {
            get {
                return ResourceManager.GetString("WindowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立窗口 的本地化字符串。
        /// </summary>
        public static string WindowSingle {
            get {
                return ResourceManager.GetString("WindowSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string zh_Hans {
            get {
                return ResourceManager.GetString("zh-Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁体中文 的本地化字符串。
        /// </summary>
        public static string zh_Hant {
            get {
                return ResourceManager.GetString("zh-Hant", resourceCulture);
            }
        }
    }
}
