//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application.Current 未初始化 的本地化字符串。
        /// </summary>
        public static string ApplicationCurrentNotInitialized {
            get {
                return ResourceManager.GetString("ApplicationCurrentNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动调整列宽 的本地化字符串。
        /// </summary>
        public static string AutoAdjustColumnWidth {
            get {
                return ResourceManager.GetString("AutoAdjustColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 的本地化字符串。
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动滚动到底部 的本地化字符串。
        /// </summary>
        public static string AutoScrollToEnd {
            get {
                return ResourceManager.GetString("AutoScrollToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动切换选中视图 的本地化字符串。
        /// </summary>
        public static string AutoSwitchSelectedView {
            get {
                return ResourceManager.GetString("AutoSwitchSelectedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份配置文件失败 的本地化字符串。
        /// </summary>
        public static string BackupConfigFileFailed {
            get {
                return ResourceManager.GetString("BackupConfigFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 baseDir 不能为空 的本地化字符串。
        /// </summary>
        public static string BaseDirCannotBeEmpty {
            get {
                return ResourceManager.GetString("BaseDirCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 batchFilePath 不能为空 的本地化字符串。
        /// </summary>
        public static string BatchFilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("BatchFilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bool2VisibilityConverter 资源未找到 的本地化字符串。
        /// </summary>
        public static string Bool2VisibilityConverterNotFound {
            get {
                return ResourceManager.GetString("Bool2VisibilityConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检测是否支持CUDA 的本地化字符串。
        /// </summary>
        public static string CheckingCUDASupport {
            get {
                return ResourceManager.GetString("CheckingCUDASupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检索是否存在附加项目 的本地化字符串。
        /// </summary>
        public static string CheckingForAdditionalProjects {
            get {
                return ResourceManager.GetString("CheckingForAdditionalProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理备份文件失败 的本地化字符串。
        /// </summary>
        public static string CleanupBackupFailed {
            get {
                return ResourceManager.GetString("CleanupBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用定时备份 的本地化字符串。
        /// </summary>
        public static string Config_EnableBackup {
            get {
                return ResourceManager.GetString("Config_EnableBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置相关参数 的本地化字符串。
        /// </summary>
        public static string Config_Parameters {
            get {
                return ResourceManager.GetString("Config_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确认删除插件{0} 的本地化字符串。
        /// </summary>
        public static string ConfirmDeletePlugin {
            get {
                return ResourceManager.GetString("ConfirmDeletePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否更新 的本地化字符串。
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前速度： 的本地化字符串。
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查依赖 {0} 版本时发生异常: {1} 的本地化字符串。
        /// </summary>
        public static string DependencyCheckException {
            get {
                return ResourceManager.GetString("DependencyCheckException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖 {0} 未找到对应的dll: {1} 的本地化字符串。
        /// </summary>
        public static string DependencyDllNotFound {
            get {
                return ResourceManager.GetString("DependencyDllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖 {0} 版本不足，要求: {1}，实际: {2} 的本地化字符串。
        /// </summary>
        public static string DependencyVersionInsufficient {
            get {
                return ResourceManager.GetString("DependencyVersionInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合: {0} 项 的本地化字符串。
        /// </summary>
        public static string DictEditor_CollectionCount {
            get {
                return ResourceManager.GetString("DictEditor_CollectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除全部 {0} 项吗？ 的本地化字符串。
        /// </summary>
        public static string DictEditor_ConfirmDeleteAll {
            get {
                return ResourceManager.GetString("DictEditor_ConfirmDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认全部删除 的本地化字符串。
        /// </summary>
        public static string DictEditor_ConfirmDeleteAllTitle {
            get {
                return ResourceManager.GetString("DictEditor_ConfirmDeleteAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除选中的 {0} 项吗？ 的本地化字符串。
        /// </summary>
        public static string DictEditor_ConfirmDeleteSelected {
            get {
                return ResourceManager.GetString("DictEditor_ConfirmDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string DictEditor_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("DictEditor_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键 (Key) 的本地化字符串。
        /// </summary>
        public static string DictEditor_Key {
            get {
                return ResourceManager.GetString("DictEditor_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑字典 的本地化字符串。
        /// </summary>
        public static string DictEditor_Title {
            get {
                return ResourceManager.GetString("DictEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 (Value) 的本地化字符串。
        /// </summary>
        public static string DictEditor_Value {
            get {
                return ResourceManager.GetString("DictEditor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前包含 {0} 个项 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_Count {
            get {
                return ResourceManager.GetString("DictItemEditor_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑列表... 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_EditList {
            get {
                return ResourceManager.GetString("DictItemEditor_EditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空列表 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_Empty {
            get {
                return ResourceManager.GetString("DictItemEditor_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键: 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_Key {
            get {
                return ResourceManager.GetString("DictItemEditor_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键不能为空！ 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_KeyEmpty {
            get {
                return ResourceManager.GetString("DictItemEditor_KeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键 &apos;{0}&apos; 已存在！请使用不同的键。 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_KeyExists {
            get {
                return ResourceManager.GetString("DictItemEditor_KeyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑字典项 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_Title {
            get {
                return ResourceManager.GetString("DictItemEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证错误 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_ValidationError {
            get {
                return ResourceManager.GetString("DictItemEditor_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值: 的本地化字符串。
        /// </summary>
        public static string DictItemEditor_Value {
            get {
                return ResourceManager.GetString("DictItemEditor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 正在备份当前版本... 的本地化字符串。
        /// </summary>
        public static string EchoBackingUpCurrentVersion {
            get {
                return ResourceManager.GetString("EchoBackingUpCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   echo 备份完成。 的本地化字符串。
        /// </summary>
        public static string EchoBackupComplete {
            get {
                return ResourceManager.GetString("EchoBackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   echo 备份到：%BKDIR% 的本地化字符串。
        /// </summary>
        public static string EchoBackupTo {
            get {
                return ResourceManager.GetString("EchoBackupTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 复制完成。 的本地化字符串。
        /// </summary>
        public static string EchoCopyComplete {
            get {
                return ResourceManager.GetString("EchoCopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 正在重新启动程序... 的本地化字符串。
        /// </summary>
        public static string EchoRestartingProgram {
            get {
                return ResourceManager.GetString("EchoRestartingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似      echo Robocopy 失败，错误码 !RC! ，尝试使用 XCOPY 回退... 的本地化字符串。
        /// </summary>
        public static string EchoRobocopyFailed {
            get {
                return ResourceManager.GetString("EchoRobocopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   echo 未找到 Robocopy，回退到 XCOPY... 的本地化字符串。
        /// </summary>
        public static string EchoRobocopyNotFound {
            get {
                return ResourceManager.GetString("EchoRobocopyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 安排延迟清理临时目录与脚本... 的本地化字符串。
        /// </summary>
        public static string EchoSchedulingCleanup {
            get {
                return ResourceManager.GetString("EchoSchedulingCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 开始复制新版本文件... 的本地化字符串。
        /// </summary>
        public static string EchoStartCopyingFiles {
            get {
                return ResourceManager.GetString("EchoStartCopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   echo 目标目录不存在，跳过备份。 的本地化字符串。
        /// </summary>
        public static string EchoTargetDirNotExist {
            get {
                return ResourceManager.GetString("EchoTargetDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 正在结束进程: {0} 的本地化字符串。
        /// </summary>
        public static string EchoTerminatingProcess {
            get {
                return ResourceManager.GetString("EchoTerminatingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 更新完成。（清理在后台进行） 的本地化字符串。
        /// </summary>
        public static string EchoUpdateComplete {
            get {
                return ResourceManager.GetString("EchoUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 echo 使用 XCOPY 回退复制... 的本地化字符串。
        /// </summary>
        public static string EchoUsingXCOPY {
            get {
                return ResourceManager.GetString("EchoUsingXCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   echo XCOPY 复制失败，更新中止。 的本地化字符串。
        /// </summary>
        public static string EchoXCOPYFailed {
            get {
                return ResourceManager.GetString("EchoXCOPYFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English（英语） 的本地化字符串。
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用浏览器搜索 的本地化字符串。
        /// </summary>
        public static string EnableBrowserSearch {
            get {
                return ResourceManager.GetString("EnableBrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用Everything搜索 的本地化字符串。
        /// </summary>
        public static string EnableEverythingSearch {
            get {
                return ResourceManager.GetString("EnableEverythingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything路径 的本地化字符串。
        /// </summary>
        public static string EverythingPath {
            get {
                return ResourceManager.GetString("EverythingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exeName 不能为空 的本地化字符串。
        /// </summary>
        public static string ExeNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ExeNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器支持正则 的本地化字符串。
        /// </summary>
        public static string FilterSupportsRegex {
            get {
                return ResourceManager.GetString("FilterSupportsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到项目{0}，{1}，是否下载 的本地化字符串。
        /// </summary>
        public static string FoundProjectDownloadConfirm {
            get {
                return ResourceManager.GetString("FoundProjectDownloadConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Français（法语） 的本地化字符串。
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用设置 的本地化字符串。
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局 的本地化字符串。
        /// </summary>
        public static string GlobalMode {
            get {
                return ResourceManager.GetString("GlobalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载热键 的本地化字符串。
        /// </summary>
        public static string HotKey_LoadHotkey {
            get {
                return ResourceManager.GetString("HotKey_LoadHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认 的本地化字符串。
        /// </summary>
        public static string HotKey_RestoreDefault {
            get {
                return ResourceManager.GetString("HotKey_RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存热键 的本地化字符串。
        /// </summary>
        public static string HotKey_SaveHotkey {
            get {
                return ResourceManager.GetString("HotKey_SaveHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲突 的本地化字符串。
        /// </summary>
        public static string HotkeyConflict {
            get {
                return ResourceManager.GetString("HotkeyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string HotkeyNormal {
            get {
                return ResourceManager.GetString("HotkeyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeys {
            get {
                return ResourceManager.GetString("HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键盘设置快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeySet1 {
            get {
                return ResourceManager.GetString("HotKeySet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击设置快捷键 的本地化字符串。
        /// </summary>
        public static string HotKeySet2 {
            get {
                return ResourceManager.GetString("HotKeySet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动选择 的本地化字符串。
        /// </summary>
        public static string IsAutoSelect {
            get {
                return ResourceManager.GetString("IsAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語（日语） 的本地化字符串。
        /// </summary>
        public static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어（韩语） 的本地化字符串。
        /// </summary>
        public static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户界面语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您必须重新启动才能使用新的语言设置 的本地化字符串。
        /// </summary>
        public static string LanguageResartSign {
            get {
                return ResourceManager.GetString("LanguageResartSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string ListEditor_Add {
            get {
                return ResourceManager.GetString("ListEditor_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除全部 {0} 项吗？ 的本地化字符串。
        /// </summary>
        public static string ListEditor_ConfirmDeleteAll {
            get {
                return ResourceManager.GetString("ListEditor_ConfirmDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认全部删除 的本地化字符串。
        /// </summary>
        public static string ListEditor_ConfirmDeleteAllTitle {
            get {
                return ResourceManager.GetString("ListEditor_ConfirmDeleteAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除选中的 {0} 项吗？ 的本地化字符串。
        /// </summary>
        public static string ListEditor_ConfirmDeleteSelected {
            get {
                return ResourceManager.GetString("ListEditor_ConfirmDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string ListEditor_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ListEditor_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string ListEditor_Delete {
            get {
                return ResourceManager.GetString("ListEditor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        public static string ListEditor_DeleteAll {
            get {
                return ResourceManager.GetString("ListEditor_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引 的本地化字符串。
        /// </summary>
        public static string ListEditor_Index {
            get {
                return ResourceManager.GetString("ListEditor_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [列表: {0} 项] 的本地化字符串。
        /// </summary>
        public static string ListEditor_ListCount {
            get {
                return ResourceManager.GetString("ListEditor_ListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string ListEditor_MoveDown {
            get {
                return ResourceManager.GetString("ListEditor_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string ListEditor_MoveUp {
            get {
                return ResourceManager.GetString("ListEditor_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑列表 的本地化字符串。
        /// </summary>
        public static string ListEditor_Title {
            get {
                return ResourceManager.GetString("ListEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string ListEditor_Value {
            get {
                return ResourceManager.GetString("ListEditor_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选框 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_Checkbox {
            get {
                return ResourceManager.GetString("ListItemEditor_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉选择 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_Dropdown {
            get {
                return ResourceManager.GetString("ListItemEditor_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑器类型: 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_EditorType {
            get {
                return ResourceManager.GetString("ListItemEditor_EditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件选择器 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_FileSelector {
            get {
                return ResourceManager.GetString("ListItemEditor_FileSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹选择器 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_FolderSelector {
            get {
                return ResourceManager.GetString("ListItemEditor_FolderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嵌套列表: 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_NestedList {
            get {
                return ResourceManager.GetString("ListItemEditor_NestedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_Textbox {
            get {
                return ResourceManager.GetString("ListItemEditor_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑项 的本地化字符串。
        /// </summary>
        public static string ListItemEditor_Title {
            get {
                return ResourceManager.GetString("ListItemEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载了没有manifest的插件: {0} 的本地化字符串。
        /// </summary>
        public static string LoadedPluginWithoutManifest {
            get {
                return ResourceManager.GetString("LoadedPluginWithoutManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载插件: {0} 的本地化字符串。
        /// </summary>
        public static string LoadingPlugin {
            get {
                return ResourceManager.GetString("LoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string Log_OpenFolder {
            get {
                return ResourceManager.GetString("Log_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒序 的本地化字符串。
        /// </summary>
        public static string Log_ReverseOrder {
            get {
                return ResourceManager.GetString("Log_ReverseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志级别 的本地化字符串。
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(_C) 的本地化字符串。
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(_C) 的本地化字符串。
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(_T) 的本地化字符串。
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(_D) 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(_E) 的本地化字符串。
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(_X) 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(_F) 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言(_L) 的本地化字符串。
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建(_N) 的本地化字符串。
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做(_R) 的本地化字符串。
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名(_M) 的本地化字符串。
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(_S) 的本地化字符串。
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为(_A) 的本地化字符串。
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选(_A) 的本地化字符串。
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板(_M) 的本地化字符串。
        /// </summary>
        public static string MenuTemplate {
            get {
                return ResourceManager.GetString("MenuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具(_T) 的本地化字符串。
        /// </summary>
        public static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Treemap 查看器 的本地化字符串。
        /// </summary>
        public static string MenuTreemapViewer {
            get {
                return ResourceManager.GetString("MenuTreemapViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销(_U) 的本地化字符串。
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图(_V) 的本地化字符串。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息日志窗口 的本地化字符串。
        /// </summary>
        public static string MsgList {
            get {
                return ResourceManager.GetString("MsgList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mysql工具 的本地化字符串。
        /// </summary>
        public static string MysqlTool {
            get {
                return ResourceManager.GetString("MysqlTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有配置本地的log4输出 的本地化字符串。
        /// </summary>
        public static string NoLocalLog4Output {
            get {
                return ResourceManager.GetString("NoLocalLog4Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线Cron表达式生成器 的本地化字符串。
        /// </summary>
        public static string OnlineCronGenerator {
            get {
                return ResourceManager.GetString("OnlineCronGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置文件 的本地化字符串。
        /// </summary>
        public static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置文件夹 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolder {
            get {
                return ResourceManager.GetString("OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所在文件夹 的本地化字符串。
        /// </summary>
        public static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志文件夹 的本地化字符串。
        /// </summary>
        public static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件DLL不存在: {0} 的本地化字符串。
        /// </summary>
        public static string PluginDllNotFound {
            get {
                return ResourceManager.GetString("PluginDllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载插件或manifest错误：{0} 的本地化字符串。
        /// </summary>
        public static string PluginLoadError {
            get {
                return ResourceManager.GetString("PluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件 {0} 缺少唯一Id，已跳过 的本地化字符串。
        /// </summary>
        public static string PluginMissingId {
            get {
                return ResourceManager.GetString("PluginMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件名称 的本地化字符串。
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到项目{0} 的本地化字符串。
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目/解决方案(_P)... 的本地化字符串。
        /// </summary>
        public static string ProjectSolution_P {
            get {
                return ResourceManager.GetString("ProjectSolution_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON 生成错误： 的本地化字符串。
        /// </summary>
        public static string PropEditor_JsonGenerateError {
            get {
                return ResourceManager.GetString("PropEditor_JsonGenerateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON 解析错误： 的本地化字符串。
        /// </summary>
        public static string PropEditor_JsonParseError {
            get {
                return ResourceManager.GetString("PropEditor_JsonParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载错误： 的本地化字符串。
        /// </summary>
        public static string PropEditor_LoadError {
            get {
                return ResourceManager.GetString("PropEditor_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可编辑的属性 的本地化字符串。
        /// </summary>
        public static string PropEditor_NoEditableProperties {
            get {
                return ResourceManager.GetString("PropEditor_NoEditableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复到默认 的本地化字符串。
        /// </summary>
        public static string PropEditor_ResetToDefault {
            get {
                return ResourceManager.GetString("PropEditor_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置到类默认值 的本地化字符串。
        /// </summary>
        public static string PropEditor_ResetTooltip {
            get {
                return ResourceManager.GetString("PropEditor_ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索属性... 的本地化字符串。
        /// </summary>
        public static string PropEditor_SearchPlaceholder {
            get {
                return ResourceManager.GetString("PropEditor_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按分类排序 (升序) 的本地化字符串。
        /// </summary>
        public static string PropEditor_SortCategoryAsc {
            get {
                return ResourceManager.GetString("PropEditor_SortCategoryAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按分类排序 (降序) 的本地化字符串。
        /// </summary>
        public static string PropEditor_SortCategoryDesc {
            get {
                return ResourceManager.GetString("PropEditor_SortCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认排序 的本地化字符串。
        /// </summary>
        public static string PropEditor_SortDefault {
            get {
                return ResourceManager.GetString("PropEditor_SortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按名称排序 (升序) 的本地化字符串。
        /// </summary>
        public static string PropEditor_SortNameAsc {
            get {
                return ResourceManager.GetString("PropEditor_SortNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按名称排序 (降序) 的本地化字符串。
        /// </summary>
        public static string PropEditor_SortNameDesc {
            get {
                return ResourceManager.GetString("PropEditor_SortNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败： 的本地化字符串。
        /// </summary>
        public static string PropEditor_ValidationError {
            get {
                return ResourceManager.GetString("PropEditor_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性编辑器窗口 的本地化字符串。
        /// </summary>
        public static string PropertyEditorWindow {
            get {
                return ResourceManager.GetString("PropertyEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   rem Robocopy 0-7 视为成功 的本地化字符串。
        /// </summary>
        public static string RemRobocopySuccess {
            get {
                return ResourceManager.GetString("RemRobocopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rem STAGE 指向临时目录中解压出的 ColorVision 内容根 的本地化字符串。
        /// </summary>
        public static string RemStagePointsToTemp {
            get {
                return ResourceManager.GetString("RemStagePointsToTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复配置文件失败 的本地化字符串。
        /// </summary>
        public static string RestoreConfigFileFailed {
            get {
                return ResourceManager.GetString("RestoreConfigFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Русский（俄语） 的本地化字符串。
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存单个配置 {0} 失败 的本地化字符串。
        /// </summary>
        public static string SaveSingleConfigFailed {
            get {
                return ResourceManager.GetString("SaveSingleConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索引擎 的本地化字符串。
        /// </summary>
        public static string SearchEngine {
            get {
                return ResourceManager.GetString("SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能排序 (升序) 的本地化字符串。
        /// </summary>
        public static string SmartSortAscending {
            get {
                return ResourceManager.GetString("SmartSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能排序 (降序) 的本地化字符串。
        /// </summary>
        public static string SmartSortDescending {
            get {
                return ResourceManager.GetString("SmartSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓冲区大小 的本地化字符串。
        /// </summary>
        public static string SocketBufferSize {
            get {
                return ResourceManager.GetString("SocketBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket管理窗口 的本地化字符串。
        /// </summary>
        public static string SocketManagementWindow {
            get {
                return ResourceManager.GetString("SocketManagementWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按分类排序 的本地化字符串。
        /// </summary>
        public static string SortByCategory {
            get {
                return ResourceManager.GetString("SortByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 {0} 排序 的本地化字符串。
        /// </summary>
        public static string SortByColumn {
            get {
                return ResourceManager.GetString("SortByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按名称排序 的本地化字符串。
        /// </summary>
        public static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认排序 的本地化字符串。
        /// </summary>
        public static string SortDefault {
            get {
                return ResourceManager.GetString("SortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序选项 的本地化字符串。
        /// </summary>
        public static string SortOptions {
            get {
                return ResourceManager.GetString("SortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均: 的本地化字符串。
        /// </summary>
        public static string TimedOp_Average {
            get {
                return ResourceManager.GetString("TimedOp_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次与历史平均接近。 的本地化字符串。
        /// </summary>
        public static string TimedOp_CloseToAverage {
            get {
                return ResourceManager.GetString("TimedOp_CloseToAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次比历史平均快 {0}。 的本地化字符串。
        /// </summary>
        public static string TimedOp_FasterThanAverage {
            get {
                return ResourceManager.GetString("TimedOp_FasterThanAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最快: 的本地化字符串。
        /// </summary>
        public static string TimedOp_Fastest {
            get {
                return ResourceManager.GetString("TimedOp_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定样本仍然较少，继续执行后会更准确。 的本地化字符串。
        /// </summary>
        public static string TimedOp_FewSamples {
            get {
                return ResourceManager.GetString("TimedOp_FewSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次: 的本地化字符串。
        /// </summary>
        public static string TimedOp_Last {
            get {
                return ResourceManager.GetString("TimedOp_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无历史耗时。 的本地化字符串。
        /// </summary>
        public static string TimedOp_NoHistory {
            get {
                return ResourceManager.GetString("TimedOp_NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定样本暂无记录。 的本地化字符串。
        /// </summary>
        public static string TimedOp_NoStableSamples {
            get {
                return ResourceManager.GetString("TimedOp_NoStableSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右键按钮可打开统计窗口。 的本地化字符串。
        /// </summary>
        public static string TimedOp_RightClickHint {
            get {
                return ResourceManager.GetString("TimedOp_RightClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次比历史平均慢 {0}。 的本地化字符串。
        /// </summary>
        public static string TimedOp_SlowerThanAverage {
            get {
                return ResourceManager.GetString("TimedOp_SlowerThanAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最慢: 的本地化字符串。
        /// </summary>
        public static string TimedOp_Slowest {
            get {
                return ResourceManager.GetString("TimedOp_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳定样本: 的本地化字符串。
        /// </summary>
        public static string TimedOp_StableSamples {
            get {
                return ResourceManager.GetString("TimedOp_StableSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时统计已记录。 的本地化字符串。
        /// </summary>
        public static string TimedOp_StatsRecorded {
            get {
                return ResourceManager.GetString("TimedOp_StatsRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看耗时统计 的本地化字符串。
        /// </summary>
        public static string TimedOp_ViewStats {
            get {
                return ResourceManager.GetString("TimedOp_ViewStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预热: 的本地化字符串。
        /// </summary>
        public static string TimedOp_Warmup {
            get {
                return ResourceManager.GetString("TimedOp_Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次软件启动的首轮样本按预热处理，不参与平均。 的本地化字符串。
        /// </summary>
        public static string TimedOp_WarmupNote {
            get {
                return ResourceManager.GetString("TimedOp_WarmupNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间： 的本地化字符串。
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览目录… 的本地化字符串。
        /// </summary>
        public static string Treemap_BrowseDirectory {
            get {
                return ResourceManager.GetString("Treemap_BrowseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要扫描的目录 的本地化字符串。
        /// </summary>
        public static string Treemap_BrowseDirectoryTooltip {
            get {
                return ResourceManager.GetString("Treemap_BrowseDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取 消 的本地化字符串。
        /// </summary>
        public static string Treemap_Cancel {
            get {
                return ResourceManager.GetString("Treemap_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消。 的本地化字符串。
        /// </summary>
        public static string Treemap_Cancelled {
            get {
                return ResourceManager.GetString("Treemap_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中止当前扫描 的本地化字符串。
        /// </summary>
        public static string Treemap_CancelTooltip {
            get {
                return ResourceManager.GetString("Treemap_CancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成。共 {0:N0} 个文件。 的本地化字符串。
        /// </summary>
        public static string Treemap_Complete {
            get {
                return ResourceManager.GetString("Treemap_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除文件：\n{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_ConfirmDelete {
            get {
                return ResourceManager.GetString("Treemap_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string Treemap_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Treemap_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制路径 的本地化字符串。
        /// </summary>
        public static string Treemap_CopyPath {
            get {
                return ResourceManager.GetString("Treemap_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_DeleteFailed {
            get {
                return ResourceManager.GetString("Treemap_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_DeleteFile {
            get {
                return ResourceManager.GetString("Treemap_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下钻取（以此为根） 的本地化字符串。
        /// </summary>
        public static string Treemap_DrillDown {
            get {
                return ResourceManager.GetString("Treemap_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘符： 的本地化字符串。
        /// </summary>
        public static string Treemap_DriveLabel {
            get {
                return ResourceManager.GetString("Treemap_DriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Treemap_Error {
            get {
                return ResourceManager.GetString("Treemap_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string Treemap_File {
            get {
                return ResourceManager.GetString("Treemap_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string Treemap_Folder {
            get {
                return ResourceManager.GetString("Treemap_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回上级 的本地化字符串。
        /// </summary>
        public static string Treemap_GoUp {
            get {
                return ResourceManager.GetString("Treemap_GoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式无效或为空。 的本地化字符串。
        /// </summary>
        public static string Treemap_InvalidFormat {
            get {
                return ResourceManager.GetString("Treemap_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加 载 的本地化字符串。
        /// </summary>
        public static string Treemap_Load {
            get {
                return ResourceManager.GetString("Treemap_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载扫描结果 的本地化字符串。
        /// </summary>
        public static string Treemap_LoadDialogTitle {
            get {
                return ResourceManager.GetString("Treemap_LoadDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_Loaded {
            get {
                return ResourceManager.GetString("Treemap_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_LoadFailed {
            get {
                return ResourceManager.GetString("Treemap_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从已保存的 JSON 文件加载扫描结果 的本地化字符串。
        /// </summary>
        public static string Treemap_LoadTooltip {
            get {
                return ResourceManager.GetString("Treemap_LoadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点数： 的本地化字符串。
        /// </summary>
        public static string Treemap_NodeCount {
            get {
                return ResourceManager.GetString("Treemap_NodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string Treemap_OpenFile {
            get {
                return ResourceManager.GetString("Treemap_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string Treemap_OpenFolder {
            get {
                return ResourceManager.GetString("Treemap_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在资源管理器中打开 的本地化字符串。
        /// </summary>
        public static string Treemap_OpenInExplorer {
            get {
                return ResourceManager.GetString("Treemap_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Treemap_Prompt {
            get {
                return ResourceManager.GetString("Treemap_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保 存 的本地化字符串。
        /// </summary>
        public static string Treemap_Save {
            get {
                return ResourceManager.GetString("Treemap_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_Saved {
            get {
                return ResourceManager.GetString("Treemap_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存扫描结果 的本地化字符串。
        /// </summary>
        public static string Treemap_SaveDialogTitle {
            get {
                return ResourceManager.GetString("Treemap_SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_SaveFailed {
            get {
                return ResourceManager.GetString("Treemap_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前扫描结果保存为 JSON 文件 的本地化字符串。
        /// </summary>
        public static string Treemap_SaveTooltip {
            get {
                return ResourceManager.GetString("Treemap_SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫 描 的本地化字符串。
        /// </summary>
        public static string Treemap_Scan {
            get {
                return ResourceManager.GetString("Treemap_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描出错：{0} 的本地化字符串。
        /// </summary>
        public static string Treemap_ScanError {
            get {
                return ResourceManager.GetString("Treemap_ScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已扫描 {0:N0} 个文件… 的本地化字符串。
        /// </summary>
        public static string Treemap_ScannedFiles {
            get {
                return ResourceManager.GetString("Treemap_ScannedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描中… 的本地化字符串。
        /// </summary>
        public static string Treemap_Scanning {
            get {
                return ResourceManager.GetString("Treemap_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描选定目录并显示树图 的本地化字符串。
        /// </summary>
        public static string Treemap_ScanTooltip {
            get {
                return ResourceManager.GetString("Treemap_ScanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择目录并点击&quot;扫描&quot;，或点击&quot;加载&quot;读取已保存的扫描结果。 的本地化字符串。
        /// </summary>
        public static string Treemap_SelectDirPrompt {
            get {
                return ResourceManager.GetString("Treemap_SelectDirPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择有效的目录。 的本地化字符串。
        /// </summary>
        public static string Treemap_SelectValidDir {
            get {
                return ResourceManager.GetString("Treemap_SelectValidDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在资源管理器中显示 的本地化字符串。
        /// </summary>
        public static string Treemap_ShowInExplorer {
            get {
                return ResourceManager.GetString("Treemap_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示标签 的本地化字符串。
        /// </summary>
        public static string Treemap_ShowLabels {
            get {
                return ResourceManager.GetString("Treemap_ShowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘空间分析 - Treemap Viewer 的本地化字符串。
        /// </summary>
        public static string Treemap_Title {
            get {
                return ResourceManager.GetString("Treemap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑ 上级 的本地化字符串。
        /// </summary>
        public static string Treemap_Up {
            get {
                return ResourceManager.GetString("Treemap_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回父目录节点 的本地化字符串。
        /// </summary>
        public static string Treemap_UpTooltip {
            get {
                return ResourceManager.GetString("Treemap_UpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的文件格式 的本地化字符串。
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新Log4Net 日志级别： 的本地化字符串。
        /// </summary>
        public static string UpdateLog4NetLevel {
            get {
                return ResourceManager.GetString("UpdateLog4NetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次更新未完成，且自动恢复失败，请手动重新安装或检查备份目录。 的本地化字符串。
        /// </summary>
        public static string UpdateRecovery_Failed {
            get {
                return ResourceManager.GetString("UpdateRecovery_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次更新未完成，已恢复到更新前版本。 的本地化字符串。
        /// </summary>
        public static string UpdateRecovery_Restored {
            get {
                return ResourceManager.GetString("UpdateRecovery_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string UseSystem {
            get {
                return ResourceManager.GetString("UseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图模式1 的本地化字符串。
        /// </summary>
        public static string ViewMode1 {
            get {
                return ResourceManager.GetString("ViewMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图模式2 的本地化字符串。
        /// </summary>
        public static string ViewMode2 {
            get {
                return ResourceManager.GetString("ViewMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图模式4 的本地化字符串。
        /// </summary>
        public static string ViewMode4 {
            get {
                return ResourceManager.GetString("ViewMode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图模式9 的本地化字符串。
        /// </summary>
        public static string ViewMode9 {
            get {
                return ResourceManager.GetString("ViewMode9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string WindowHidden {
            get {
                return ResourceManager.GetString("WindowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立窗口 的本地化字符串。
        /// </summary>
        public static string WindowSingle {
            get {
                return ResourceManager.GetString("WindowSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入配置文件 {0} 失败 的本地化字符串。
        /// </summary>
        public static string WriteConfigFileFailed {
            get {
                return ResourceManager.GetString("WriteConfigFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string zh_Hans {
            get {
                return ResourceManager.GetString("zh-Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文（繁体中文） 的本地化字符串。
        /// </summary>
        public static string zh_Hant {
            get {
                return ResourceManager.GetString("zh-Hant", resourceCulture);
            }
        }
    }
}
