//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProjector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProjector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法加载图片.
        /// </summary>
        public static string FailedToLoadImage {
            get {
                return ResourceManager.GetString("FailedToLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法开始投影.
        /// </summary>
        public static string FailedToStartProjection {
            get {
                return ResourceManager.GetString("FailedToStartProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件不存在.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件|*.tif;*.tiff;*.png;*.jpg;*.jpeg;*.bmp|TIF 文件|*.tif;*.tiff|PNG 文件|*.png|JPEG 文件|*.jpg;*.jpeg|BMP 文件|*.bmp|所有文件|*.*.
        /// </summary>
        public static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已加载图片.
        /// </summary>
        public static string ImageLoaded {
            get {
                return ResourceManager.GetString("ImageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片预览.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片投影工具.
        /// </summary>
        public static string ImageProjector {
            get {
                return ResourceManager.GetString("ImageProjector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片选择.
        /// </summary>
        public static string ImageSelection {
            get {
                return ResourceManager.GetString("ImageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示器选择.
        /// </summary>
        public static string MonitorSelection {
            get {
                return ResourceManager.GetString("MonitorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按 ESC 键关闭.
        /// </summary>
        public static string PressEscToClose {
            get {
                return ResourceManager.GetString("PressEscToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主显示器.
        /// </summary>
        public static string PrimaryMonitor {
            get {
                return ResourceManager.GetString("PrimaryMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影中... 按 ESC 键关闭.
        /// </summary>
        public static string ProjectionStarted {
            get {
                return ResourceManager.GetString("ProjectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影已停止.
        /// </summary>
        public static string ProjectionStopped {
            get {
                return ResourceManager.GetString("ProjectionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 副显示器.
        /// </summary>
        public static string SecondaryMonitor {
            get {
                return ResourceManager.GetString("SecondaryMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择图片文件.
        /// </summary>
        public static string SelectImageFile {
            get {
                return ResourceManager.GetString("SelectImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择图片和显示器.
        /// </summary>
        public static string SelectImageFirst {
            get {
                return ResourceManager.GetString("SelectImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止投影.
        /// </summary>
        public static string StopProjection {
            get {
                return ResourceManager.GetString("StopProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持格式: TIF, PNG, JPG, BMP.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标显示器:.
        /// </summary>
        public static string TargetMonitor {
            get {
                return ResourceManager.GetString("TargetMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
