//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局 的本地化字符串。
        /// </summary>
        internal static string GlobalMode {
            get {
                return ResourceManager.GetString("GlobalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲突 的本地化字符串。
        /// </summary>
        internal static string HotkeyConflict {
            get {
                return ResourceManager.GetString("HotkeyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string HotkeyNormal {
            get {
                return ResourceManager.GetString("HotkeyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键盘设置快捷键 的本地化字符串。
        /// </summary>
        internal static string HotKeySet1 {
            get {
                return ResourceManager.GetString("HotKeySet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击设置快捷键 的本地化字符串。
        /// </summary>
        internal static string HotKeySet2 {
            get {
                return ResourceManager.GetString("HotKeySet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩语 的本地化字符串。
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您必须重新启动才能使用新的语言设置 的本地化字符串。
        /// </summary>
        internal static string LanguageResartSign {
            get {
                return ResourceManager.GetString("LanguageResartSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(_F) 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板(_M) 的本地化字符串。
        /// </summary>
        internal static string MenuTemplate {
            get {
                return ResourceManager.GetString("MenuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具(_T) 的本地化字符串。
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        internal static string UseSystem {
            get {
                return ResourceManager.GetString("UseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string zh_Hans {
            get {
                return ResourceManager.GetString("zh-Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁体中文 的本地化字符串。
        /// </summary>
        internal static string zh_Hant {
            get {
                return ResourceManager.GetString("zh-Hant", resourceCulture);
            }
        }
    }
}
