//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.ImageEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.ImageEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绝对值 的本地化字符串。
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整亮度和对比度 的本地化字符串。
        /// </summary>
        public static string Algorithm_AdjustBrightnessContrast {
            get {
                return ResourceManager.GetString("Algorithm_AdjustBrightnessContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整伽马值 的本地化字符串。
        /// </summary>
        public static string Algorithm_AdjustGamma {
            get {
                return ResourceManager.GetString("Algorithm_AdjustGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整阈值 的本地化字符串。
        /// </summary>
        public static string Algorithm_AdjustThreshold {
            get {
                return ResourceManager.GetString("Algorithm_AdjustThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整白平衡 的本地化字符串。
        /// </summary>
        public static string Algorithm_AdjustWhiteBalance {
            get {
                return ResourceManager.GetString("Algorithm_AdjustWhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法调用 的本地化字符串。
        /// </summary>
        public static string Algorithm_AlgorithmCalls {
            get {
                return ResourceManager.GetString("Algorithm_AlgorithmCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Algorithm_Apply {
            get {
                return ResourceManager.GetString("Algorithm_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝色 的本地化字符串。
        /// </summary>
        public static string Algorithm_Blue {
            get {
                return ResourceManager.GetString("Algorithm_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        public static string Algorithm_Brightness {
            get {
                return ResourceManager.GetString("Algorithm_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度对比度调整 的本地化字符串。
        /// </summary>
        public static string Algorithm_BrightnessContrastTitle {
            get {
                return ResourceManager.GetString("Algorithm_BrightnessContrastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Algorithm_Cancel {
            get {
                return ResourceManager.GetString("Algorithm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比度 的本地化字符串。
        /// </summary>
        public static string Algorithm_Contrast {
            get {
                return ResourceManager.GetString("Algorithm_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边缘检测 (Canny) 的本地化字符串。
        /// </summary>
        public static string Algorithm_EdgeDetectionTitle {
            get {
                return ResourceManager.GetString("Algorithm_EdgeDetectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伽马校正 的本地化字符串。
        /// </summary>
        public static string Algorithm_GammaCorrectionTitle {
            get {
                return ResourceManager.GetString("Algorithm_GammaCorrectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伽马值 的本地化字符串。
        /// </summary>
        public static string Algorithm_GammaValue {
            get {
                return ResourceManager.GetString("Algorithm_GammaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高斯模糊 的本地化字符串。
        /// </summary>
        public static string Algorithm_GaussianBlurTitle {
            get {
                return ResourceManager.GetString("Algorithm_GaussianBlurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色 的本地化字符串。
        /// </summary>
        public static string Algorithm_Green {
            get {
                return ResourceManager.GetString("Algorithm_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高阈值: 的本地化字符串。
        /// </summary>
        public static string Algorithm_HighThreshold {
            get {
                return ResourceManager.GetString("Algorithm_HighThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核大小 (必须为奇数): 的本地化字符串。
        /// </summary>
        public static string Algorithm_KernelSizeOdd {
            get {
                return ResourceManager.GetString("Algorithm_KernelSizeOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低阈值: 的本地化字符串。
        /// </summary>
        public static string Algorithm_LowThreshold {
            get {
                return ResourceManager.GetString("Algorithm_LowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中值滤波 的本地化字符串。
        /// </summary>
        public static string Algorithm_MedianBlurTitle {
            get {
                return ResourceManager.GetString("Algorithm_MedianBlurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红色 的本地化字符串。
        /// </summary>
        public static string Algorithm_Red {
            get {
                return ResourceManager.GetString("Algorithm_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFR/MTF 分析 的本地化字符串。
        /// </summary>
        public static string Algorithm_SfrMtfAnalysis {
            get {
                return ResourceManager.GetString("Algorithm_SfrMtfAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sigma (标准差): 的本地化字符串。
        /// </summary>
        public static string Algorithm_SigmaStdDev {
            get {
                return ResourceManager.GetString("Algorithm_SigmaStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阈值处理 的本地化字符串。
        /// </summary>
        public static string Algorithm_ThresholdTitle {
            get {
                return ResourceManager.GetString("Algorithm_ThresholdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阈值 的本地化字符串。
        /// </summary>
        public static string Algorithm_ThresholdValue {
            get {
                return ResourceManager.GetString("Algorithm_ThresholdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白平衡调整 的本地化字符串。
        /// </summary>
        public static string Algorithm_WhiteBalanceTitle {
            get {
                return ResourceManager.GetString("Algorithm_WhiteBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从图像中提取有效的截面数据。 的本地化字符串。
        /// </summary>
        public static string Annotation_CannotExtractData {
            get {
                return ResourceManager.GetString("Annotation_CannotExtractData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该图形没有足够的点来生成切面图。 的本地化字符串。
        /// </summary>
        public static string Annotation_NotEnoughPoints {
            get {
                return ResourceManager.GetString("Annotation_NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个采样点 的本地化字符串。
        /// </summary>
        public static string Annotation_SamplePoints {
            get {
                return ResourceManager.GetString("Annotation_SamplePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切面图 的本地化字符串。
        /// </summary>
        public static string Annotation_SectionalDrawingTitle {
            get {
                return ResourceManager.GetString("Annotation_SectionalDrawingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像源不是可读的 WriteableBitmap 格式。 的本地化字符串。
        /// </summary>
        public static string Annotation_SourceNotReadable {
            get {
                return ResourceManager.GetString("Annotation_SourceNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度评估 的本地化字符串。
        /// </summary>
        public static string Artculation_MenuHeader {
            get {
                return ResourceManager.GetString("Artculation_MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度评估参数设置 的本地化字符串。
        /// </summary>
        public static string Artculation_ParamSettings {
            get {
                return ResourceManager.GetString("Artculation_ParamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像清晰度评估结果: 的本地化字符串。
        /// </summary>
        public static string Artculation_ResultMsg {
            get {
                return ResourceManager.GetString("Artculation_ResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清晰度评估 的本地化字符串。
        /// </summary>
        public static string Artculation_ResultTitle {
            get {
                return ResourceManager.GetString("Artculation_ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动色阶调整 的本地化字符串。
        /// </summary>
        public static string AutoLevelsAdjustment {
            get {
                return ResourceManager.GetString("AutoLevelsAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放质量 的本地化字符串。
        /// </summary>
        public static string BitmapScalingMode {
            get {
                return ResourceManager.GetString("BitmapScalingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边缘检测 (Canny) 的本地化字符串。
        /// </summary>
        public static string Canny {
            get {
                return ResourceManager.GetString("Canny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影视 的本地化字符串。
        /// </summary>
        public static string Cie_Cinema {
            get {
                return ResourceManager.GetString("Cie_Cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Cie_Clear {
            get {
                return ResourceManager.GetString("Cie_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色域 的本地化字符串。
        /// </summary>
        public static string Cie_ColorGamut {
            get {
                return ResourceManager.GetString("Cie_ColorGamut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标系 的本地化字符串。
        /// </summary>
        public static string Cie_CoordinateSystem {
            get {
                return ResourceManager.GetString("Cie_CoordinateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前点 的本地化字符串。
        /// </summary>
        public static string Cie_CurrentPoint {
            get {
                return ResourceManager.GetString("Cie_CurrentPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示器 的本地化字符串。
        /// </summary>
        public static string Cie_Display {
            get {
                return ResourceManager.GetString("Cie_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示预设 的本地化字符串。
        /// </summary>
        public static string Cie_DisplayPresets {
            get {
                return ResourceManager.GetString("Cie_DisplayPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适应 的本地化字符串。
        /// </summary>
        public static string Cie_Fit {
            get {
                return ResourceManager.GetString("Cie_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参考线 的本地化字符串。
        /// </summary>
        public static string Cie_ReferenceLines {
            get {
                return ResourceManager.GetString("Cie_ReferenceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string Cie_SelectAll {
            get {
                return ResourceManager.GetString("Cie_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CIE 色度图 的本地化字符串。
        /// </summary>
        public static string Cie_Title {
            get {
                return ResourceManager.GetString("Cie_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白点 / 光源 的本地化字符串。
        /// </summary>
        public static string Cie_WhitePointLightSource {
            get {
                return ResourceManager.GetString("Cie_WhitePointLightSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空(_C) 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伪彩色 的本地化字符串。
        /// </summary>
        public static string ColormapTypes {
            get {
                return ResourceManager.GetString("ColormapTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        public static string Draw_Color {
            get {
                return ResourceManager.GetString("Draw_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续绘制 的本地化字符串。
        /// </summary>
        public static string Draw_ContinuousDraw {
            get {
                return ResourceManager.GetString("Draw_ContinuousDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以中心创建 的本地化字符串。
        /// </summary>
        public static string Draw_CreateFromCenter {
            get {
                return ResourceManager.GetString("Draw_CreateFromCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认颜色 的本地化字符串。
        /// </summary>
        public static string Draw_DefaultColor {
            get {
                return ResourceManager.GetString("Draw_DefaultColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认字号 的本地化字符串。
        /// </summary>
        public static string Draw_DefaultFontSize {
            get {
                return ResourceManager.GetString("Draw_DefaultFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Draw_Delete {
            get {
                return ResourceManager.GetString("Draw_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Draw_Edit {
            get {
                return ResourceManager.GetString("Draw_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Draw_Error {
            get {
                return ResourceManager.GetString("Draw_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充 的本地化字符串。
        /// </summary>
        public static string Draw_Fill {
            get {
                return ResourceManager.GetString("Draw_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随缩放 的本地化字符串。
        /// </summary>
        public static string Draw_FollowZoom {
            get {
                return ResourceManager.GetString("Draw_FollowZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        public static string Draw_FontSize {
            get {
                return ResourceManager.GetString("Draw_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荧光笔模式 的本地化字符串。
        /// </summary>
        public static string Draw_HighlighterMode {
            get {
                return ResourceManager.GetString("Draw_HighlighterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线条颜色 的本地化字符串。
        /// </summary>
        public static string Draw_LineColor {
            get {
                return ResourceManager.GetString("Draw_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线宽 的本地化字符串。
        /// </summary>
        public static string Draw_LineWidth {
            get {
                return ResourceManager.GetString("Draw_LineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        public static string Draw_Lock {
            get {
                return ResourceManager.GetString("Draw_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定默认半径 的本地化字符串。
        /// </summary>
        public static string Draw_LockDefaultRadius {
            get {
                return ResourceManager.GetString("Draw_LockDefaultRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定默认尺寸 的本地化字符串。
        /// </summary>
        public static string Draw_LockDefaultSize {
            get {
                return ResourceManager.GetString("Draw_LockDefaultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格化 的本地化字符串。
        /// </summary>
        public static string Draw_Rasterize {
            get {
                return ResourceManager.GetString("Draw_Rasterize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为图像中心 的本地化字符串。
        /// </summary>
        public static string Draw_ResetToImageCenter {
            get {
                return ResourceManager.GetString("Draw_ResetToImageCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采样间距 的本地化字符串。
        /// </summary>
        public static string Draw_SampleSpacing {
            get {
                return ResourceManager.GetString("Draw_SampleSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 笔宽 的本地化字符串。
        /// </summary>
        public static string Draw_StrokeWidth {
            get {
                return ResourceManager.GetString("Draw_StrokeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public static string Draw_Text {
            get {
                return ResourceManager.GetString("Draw_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Draw_Tip {
            get {
                return ResourceManager.GetString("Draw_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Draw_Warning {
            get {
                return ResourceManager.GetString("Draw_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外切 的本地化字符串。
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平翻转(_H) 的本地化字符串。
        /// </summary>
        public static string FlipHorizontal {
            get {
                return ResourceManager.GetString("FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直翻转(_V) 的本地化字符串。
        /// </summary>
        public static string FlipVertical {
            get {
                return ResourceManager.GetString("FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伽马校正 的本地化字符串。
        /// </summary>
        public static string GammaCorrection {
            get {
                return ResourceManager.GetString("GammaCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高斯模糊 的本地化字符串。
        /// </summary>
        public static string GaussianBlur {
            get {
                return ResourceManager.GetString("GaussianBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度: 的本地化字符串。
        /// </summary>
        public static string Graphic_Angle {
            get {
                return ResourceManager.GetString("Graphic_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点阵数的行列不能小于1 的本地化字符串。
        /// </summary>
        public static string Graphic_ArrayCountMin1 {
            get {
                return ResourceManager.GetString("Graphic_ArrayCountMin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下: 的本地化字符串。
        /// </summary>
        public static string Graphic_Bottom {
            get {
                return ResourceManager.GetString("Graphic_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下 的本地化字符串。
        /// </summary>
        public static string Graphic_BottomLeft {
            get {
                return ResourceManager.GetString("Graphic_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下 的本地化字符串。
        /// </summary>
        public static string Graphic_BottomRight {
            get {
                return ResourceManager.GetString("Graphic_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心点 的本地化字符串。
        /// </summary>
        public static string Graphic_CenterPoint {
            get {
                return ResourceManager.GetString("Graphic_CenterPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆 的本地化字符串。
        /// </summary>
        public static string Graphic_Circle {
            get {
                return ResourceManager.GetString("Graphic_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆形 的本地化字符串。
        /// </summary>
        public static string Graphic_CircleShape {
            get {
                return ResourceManager.GetString("Graphic_CircleShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Graphic_ClearAll {
            get {
                return ResourceManager.GetString("Graphic_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列数: 的本地化字符串。
        /// </summary>
        public static string Graphic_Columns {
            get {
                return ResourceManager.GetString("Graphic_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量: 的本地化字符串。
        /// </summary>
        public static string Graphic_Count {
            get {
                return ResourceManager.GetString("Graphic_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制的个数不能小于1 的本地化字符串。
        /// </summary>
        public static string Graphic_CountMin1 {
            get {
                return ResourceManager.GetString("Graphic_CountMin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制 的本地化字符串。
        /// </summary>
        public static string Graphic_Draw {
            get {
                return ResourceManager.GetString("Graphic_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寻找发光区角点 的本地化字符串。
        /// </summary>
        public static string Graphic_FindLuminousAreaCorner {
            get {
                return ResourceManager.GetString("Graphic_FindLuminousAreaCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度: 的本地化字符串。
        /// </summary>
        public static string Graphic_Height {
            get {
                return ResourceManager.GetString("Graphic_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像设置 的本地化字符串。
        /// </summary>
        public static string Graphic_ImageViewSettings {
            get {
                return ResourceManager.GetString("Graphic_ImageViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左: 的本地化字符串。
        /// </summary>
        public static string Graphic_Left {
            get {
                return ResourceManager.GetString("Graphic_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四边形 的本地化字符串。
        /// </summary>
        public static string Graphic_Quadrilateral {
            get {
                return ResourceManager.GetString("Graphic_Quadrilateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半径: 的本地化字符串。
        /// </summary>
        public static string Graphic_Radius {
            get {
                return ResourceManager.GetString("Graphic_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 的本地化字符串。
        /// </summary>
        public static string Graphic_RectShape {
            get {
                return ResourceManager.GetString("Graphic_RectShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右: 的本地化字符串。
        /// </summary>
        public static string Graphic_Right {
            get {
                return ResourceManager.GetString("Graphic_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数: 的本地化字符串。
        /// </summary>
        public static string Graphic_Rows {
            get {
                return ResourceManager.GetString("Graphic_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Graphic_Set {
            get {
                return ResourceManager.GetString("Graphic_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置布点区域 的本地化字符串。
        /// </summary>
        public static string Graphic_SetPoiArea {
            get {
                return ResourceManager.GetString("Graphic_SetPoiArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上: 的本地化字符串。
        /// </summary>
        public static string Graphic_Top {
            get {
                return ResourceManager.GetString("Graphic_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上 的本地化字符串。
        /// </summary>
        public static string Graphic_TopLeft {
            get {
                return ResourceManager.GetString("Graphic_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上 的本地化字符串。
        /// </summary>
        public static string Graphic_TopRight {
            get {
                return ResourceManager.GetString("Graphic_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度: 的本地化字符串。
        /// </summary>
        public static string Graphic_Width {
            get {
                return ResourceManager.GetString("Graphic_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直方图 (Histogram) 的本地化字符串。
        /// </summary>
        public static string Histogram_Title {
            get {
                return ResourceManager.GetString("Histogram_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直方图均衡化 的本地化字符串。
        /// </summary>
        public static string HistogramEqualization {
            get {
                return ResourceManager.GetString("HistogramEqualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像算法 的本地化字符串。
        /// </summary>
        public static string ImageAlgorithm {
            get {
                return ResourceManager.GetString("ImageAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出标注 的本地化字符串。
        /// </summary>
        public static string ImageView_ExportAnnotations {
            get {
                return ResourceManager.GetString("ImageView_ExportAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出 {0} 个标注。 的本地化字符串。
        /// </summary>
        public static string ImageView_ExportedAnnotations {
            get {
                return ResourceManager.GetString("ImageView_ExportedAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出 {0} 个标注，跳过 {1} 个未接入 annotation 的图元。 的本地化字符串。
        /// </summary>
        public static string ImageView_ExportedAnnotationsWithSkip {
            get {
                return ResourceManager.GetString("ImageView_ExportedAnnotationsWithSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入标注 的本地化字符串。
        /// </summary>
        public static string ImageView_ImportAnnotations {
            get {
                return ResourceManager.GetString("ImageView_ImportAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入标注失败: {0} 的本地化字符串。
        /// </summary>
        public static string ImageView_ImportAnnotationsFailed {
            get {
                return ResourceManager.GetString("ImageView_ImportAnnotationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导入 {0} 个标注。 的本地化字符串。
        /// </summary>
        public static string ImageView_ImportedAnnotations {
            get {
                return ResourceManager.GetString("ImageView_ImportedAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像通道数 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_Channel {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像列数 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_Cols {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_Cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像位深 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_Depth {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像水平 DPI 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_DpiX {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_DpiX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像垂直 DPI 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_DpiY {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_DpiY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前打开图像的绝对路径 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_FilePath {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前打开文件大小（字节） 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_FileSize {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像像素格式 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_PixelFormat {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像行数 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_Rows {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像 stride 的本地化字符串。
        /// </summary>
        public static string ImageView_MetadataDesc_Stride {
            get {
                return ResourceManager.GetString("ImageView_MetadataDesc_Stride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图元里没有已接入 annotation 的类型。 的本地化字符串。
        /// </summary>
        public static string ImageView_NoAnnotationTypes {
            get {
                return ResourceManager.GetString("ImageView_NoAnnotationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有可导出的标注。 的本地化字符串。
        /// </summary>
        public static string ImageView_NoExportableAnnotations {
            get {
                return ResourceManager.GetString("ImageView_NoExportableAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像元数据 的本地化字符串。
        /// </summary>
        public static string ImageView_Scope_ImageMetadata {
            get {
                return ResourceManager.GetString("ImageView_Scope_ImageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开器运行态 的本地化字符串。
        /// </summary>
        public static string ImageView_Scope_OpenerRuntime {
            get {
                return ResourceManager.GetString("ImageView_Scope_OpenerRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前视窗状态 的本地化字符串。
        /// </summary>
        public static string ImageView_Scope_ViewState {
            get {
                return ResourceManager.GetString("ImageView_Scope_ViewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由当前文件和像素内容决定，切换图像后会整体刷新。 的本地化字符串。
        /// </summary>
        public static string ImageView_ScopeDesc_ImageMetadata {
            get {
                return ResourceManager.GetString("ImageView_ScopeDesc_ImageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只在特定打开器工作流里有意义的运行态信息。 的本地化字符串。
        /// </summary>
        public static string ImageView_ScopeDesc_OpenerRuntime {
            get {
                return ResourceManager.GetString("ImageView_ScopeDesc_OpenerRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只作用于当前 ImageView 的临时状态，不会写回全局默认值。 的本地化字符串。
        /// </summary>
        public static string ImageView_ScopeDesc_ViewState {
            get {
                return ResourceManager.GetString("ImageView_ScopeDesc_ViewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的图片格式 {0} 的本地化字符串。
        /// </summary>
        public static string ImageView_UnsupportedImageFormat {
            get {
                return ResourceManager.GetString("ImageView_UnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}暂不支持的格式,请联系开发人员 的本地化字符串。
        /// </summary>
        public static string ImageView_UnsupportedPixelFormat {
            get {
                return ResourceManager.GetString("ImageView_UnsupportedPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内切 的本地化字符串。
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反相 的本地化字符串。
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 的本地化字符串。
        /// </summary>
        public static string IsLayoutUpdated {
            get {
                return ResourceManager.GetString("IsLayoutUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示消息 的本地化字符串。
        /// </summary>
        public static string IsShowMsg {
            get {
                return ResourceManager.GetString("IsShowMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示文字 的本地化字符串。
        /// </summary>
        public static string IsShowText {
            get {
                return ResourceManager.GetString("IsShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线上 的本地化字符串。
        /// </summary>
        public static string LineOn {
            get {
                return ResourceManager.GetString("LineOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度对比度调整 的本地化字符串。
        /// </summary>
        public static string LuminanceContrastAdjustment {
            get {
                return ResourceManager.GetString("LuminanceContrastAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中值滤波 的本地化字符串。
        /// </summary>
        public static string MedianFilter {
            get {
                return ResourceManager.GetString("MedianFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D模型查看器 的本地化字符串。
        /// </summary>
        public static string MenuModelViewer3D {
            get {
                return ResourceManager.GetString("MenuModelViewer3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去除摩尔纹 的本地化字符串。
        /// </summary>
        public static string MoireRemove {
            get {
                return ResourceManager.GetString("MoireRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(_O) 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性(_R) 的本地化字符串。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前伪彩色 的本地化字符串。
        /// </summary>
        public static string PseudoColor_CurrentPseudoColor {
            get {
                return ResourceManager.GetString("PseudoColor_CurrentPseudoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伪彩色默认值 的本地化字符串。
        /// </summary>
        public static string PseudoColor_DefaultPseudoColor {
            get {
                return ResourceManager.GetString("PseudoColor_DefaultPseudoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伪彩色 的本地化字符串。
        /// </summary>
        public static string PseudoColor_Group {
            get {
                return ResourceManager.GetString("PseudoColor_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对值 的本地化字符串。
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像旋转 的本地化字符串。
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左旋转(_L) 的本地化字符串。
        /// </summary>
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右旋转(_R) 的本地化字符串。
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际距离 的本地化字符串。
        /// </summary>
        public static string Ruler_ActualDistance {
            get {
                return ResourceManager.GetString("Ruler_ActualDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        public static string Ruler_Calculate {
            get {
                return ResourceManager.GetString("Ruler_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量是否启用实际单位 的本地化字符串。
        /// </summary>
        public static string Ruler_MeasureWithRealUnits {
            get {
                return ResourceManager.GetString("Ruler_MeasureWithRealUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理比例 的本地化字符串。
        /// </summary>
        public static string Ruler_PhysicalScale {
            get {
                return ResourceManager.GetString("Ruler_PhysicalScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理单位 的本地化字符串。
        /// </summary>
        public static string Ruler_PhysicalUnit {
            get {
                return ResourceManager.GetString("Ruler_PhysicalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        public static string Ruler_Pixel {
            get {
                return ResourceManager.GetString("Ruler_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1个像素代表实际 的本地化字符串。
        /// </summary>
        public static string Ruler_PixelRepresents {
            get {
                return ResourceManager.GetString("Ruler_PixelRepresents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点 的本地化字符串。
        /// </summary>
        public static string Ruler_StartPoint {
            get {
                return ResourceManager.GetString("Ruler_StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总长 的本地化字符串。
        /// </summary>
        public static string Ruler_TotalLength {
            get {
                return ResourceManager.GetString("Ruler_TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截屏 的本地化字符串。
        /// </summary>
        public static string SaveAsImage {
            get {
                return ResourceManager.GetString("SaveAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切面图 的本地化字符串。
        /// </summary>
        public static string SectionalDrawing {
            get {
                return ResourceManager.GetString("SectionalDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部工具栏 (ToolBarAl) 的本地化字符串。
        /// </summary>
        public static string Settings_BottomToolbar {
            get {
                return ResourceManager.GetString("Settings_BottomToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认显示参数 的本地化字符串。
        /// </summary>
        public static string Settings_DefaultDisplayParams {
            get {
                return ResourceManager.GetString("Settings_DefaultDisplayParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认图像缩放 的本地化字符串。
        /// </summary>
        public static string Settings_DefaultImageScaling {
            get {
                return ResourceManager.GetString("Settings_DefaultImageScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认实时相机参数 的本地化字符串。
        /// </summary>
        public static string Settings_DefaultRealtimeCameraParams {
            get {
                return ResourceManager.GetString("Settings_DefaultRealtimeCameraParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认文本样式 的本地化字符串。
        /// </summary>
        public static string Settings_DefaultTextStyle {
            get {
                return ResourceManager.GetString("Settings_DefaultTextStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制工具栏 (ToolBarDraw) 的本地化字符串。
        /// </summary>
        public static string Settings_DrawToolbar {
            get {
                return ResourceManager.GetString("Settings_DrawToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 项 的本地化字符串。
        /// </summary>
        public static string Settings_EntryCount {
            get {
                return ResourceManager.GetString("Settings_EntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下文 的本地化字符串。
        /// </summary>
        public static string Settings_GroupContext {
            get {
                return ResourceManager.GetString("Settings_GroupContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        public static string Settings_GroupDefaults {
            get {
                return ResourceManager.GetString("Settings_GroupDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Settings_GroupDisplay {
            get {
                return ResourceManager.GetString("Settings_GroupDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用 的本地化字符串。
        /// </summary>
        public static string Settings_GroupGeneral {
            get {
                return ResourceManager.GetString("Settings_GroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载器 的本地化字符串。
        /// </summary>
        public static string Settings_GroupLoader {
            get {
                return ResourceManager.GetString("Settings_GroupLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作台 的本地化字符串。
        /// </summary>
        public static string Settings_GroupWorkspace {
            get {
                return ResourceManager.GetString("Settings_GroupWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像打开器 的本地化字符串。
        /// </summary>
        public static string Settings_ImageOpeners {
            get {
                return ResourceManager.GetString("Settings_ImageOpeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像设置 的本地化字符串。
        /// </summary>
        public static string Settings_ImageSettingsTitle {
            get {
                return ResourceManager.GetString("Settings_ImageSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧工具栏 (ToolBarLeft) 的本地化字符串。
        /// </summary>
        public static string Settings_LeftToolbar {
            get {
                return ResourceManager.GetString("Settings_LeftToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理尺寸默认值 的本地化字符串。
        /// </summary>
        public static string Settings_PhysicalSizeDefaults {
            get {
                return ResourceManager.GetString("Settings_PhysicalSizeDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Settings_Refresh {
            get {
                return ResourceManager.GetString("Settings_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧工具栏 (ToolBarRight) 的本地化字符串。
        /// </summary>
        public static string Settings_RightToolbar {
            get {
                return ResourceManager.GetString("Settings_RightToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIF 打开器 的本地化字符串。
        /// </summary>
        public static string Settings_TifOpener {
            get {
                return ResourceManager.GetString("Settings_TifOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏可见性 的本地化字符串。
        /// </summary>
        public static string Settings_ToolbarVisibility {
            get {
                return ResourceManager.GetString("Settings_ToolbarVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部工具栏 (ToolBarTop) 的本地化字符串。
        /// </summary>
        public static string Settings_TopToolbar {
            get {
                return ResourceManager.GetString("Settings_TopToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Sfr_ExportFailed {
            get {
                return ResourceManager.GetString("Sfr_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        public static string Sfr_ExportSuccess {
            get {
                return ResourceManager.GetString("Sfr_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已成功导出到: 的本地化字符串。
        /// </summary>
        public static string Sfr_ExportSuccessMsg {
            get {
                return ResourceManager.GetString("Sfr_ExportSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到对应频率 的本地化字符串。
        /// </summary>
        public static string Sfr_FreqNotFound {
            get {
                return ResourceManager.GetString("Sfr_FreqNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率输入错误 的本地化字符串。
        /// </summary>
        public static string Sfr_FrequencyInputError {
            get {
                return ResourceManager.GetString("Sfr_FrequencyInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MTF输入错误 的本地化字符串。
        /// </summary>
        public static string Sfr_MtfInputError {
            get {
                return ResourceManager.GetString("Sfr_MtfInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到对应MTF 的本地化字符串。
        /// </summary>
        public static string Sfr_MtfNotFound {
            get {
                return ResourceManager.GetString("Sfr_MtfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锐化 的本地化字符串。
        /// </summary>
        public static string Sharpening {
            get {
                return ResourceManager.GetString("Sharpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改后需点击应用重新渲染 的本地化字符串。
        /// </summary>
        public static string ThreeD_ApplyNote {
            get {
                return ResourceManager.GetString("ThreeD_ApplyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用并刷新 的本地化字符串。
        /// </summary>
        public static string ThreeD_ApplyRefresh {
            get {
                return ResourceManager.GetString("ThreeD_ApplyRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后 的本地化字符串。
        /// </summary>
        public static string ThreeD_Back {
            get {
                return ResourceManager.GetString("ThreeD_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_BackViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_BackViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下 的本地化字符串。
        /// </summary>
        public static string ThreeD_Bottom {
            get {
                return ResourceManager.GetString("ThreeD_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_BottomViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_BottomViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        public static string ThreeD_Camera {
            get {
                return ResourceManager.GetString("ThreeD_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机位置 的本地化字符串。
        /// </summary>
        public static string ThreeD_CameraPosition {
            get {
                return ResourceManager.GetString("ThreeD_CameraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减少高度 (Num- / -) 的本地化字符串。
        /// </summary>
        public static string ThreeD_DecreaseHeightToolTip {
            get {
                return ResourceManager.GetString("ThreeD_DecreaseHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出模型 的本地化字符串。
        /// </summary>
        public static string ThreeD_ExportModel {
            get {
                return ResourceManager.GetString("ThreeD_ExportModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出当前3D网格为 OBJ 或 STL 的本地化字符串。
        /// </summary>
        public static string ThreeD_ExportModelToolTip {
            get {
                return ResourceManager.GetString("ThreeD_ExportModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string ThreeD_File {
            get {
                return ResourceManager.GetString("ThreeD_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 的本地化字符串。
        /// </summary>
        public static string ThreeD_Front {
            get {
                return ResourceManager.GetString("ThreeD_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_FrontViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_FrontViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public static string ThreeD_Height {
            get {
                return ResourceManager.GetString("ThreeD_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度缩放 的本地化字符串。
        /// </summary>
        public static string ThreeD_HeightScale {
            get {
                return ResourceManager.GetString("ThreeD_HeightScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加高度 (Num+ / +) 的本地化字符串。
        /// </summary>
        public static string ThreeD_IncreaseHeightToolTip {
            get {
                return ResourceManager.GetString("ThreeD_IncreaseHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隔离选中 的本地化字符串。
        /// </summary>
        public static string ThreeD_IsolateSelected {
            get {
                return ResourceManager.GetString("ThreeD_IsolateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等轴视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_IsoViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_IsoViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        public static string ThreeD_Left {
            get {
                return ResourceManager.GetString("ThreeD_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_LeftViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_LeftViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视角方向 的本地化字符串。
        /// </summary>
        public static string ThreeD_LookDirection {
            get {
                return ResourceManager.GetString("ThreeD_LookDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下看 (C) 的本地化字符串。
        /// </summary>
        public static string ThreeD_LookDownToolTip {
            get {
                return ResourceManager.GetString("ThreeD_LookDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左看 (D) 的本地化字符串。
        /// </summary>
        public static string ThreeD_LookLeftToolTip {
            get {
                return ResourceManager.GetString("ThreeD_LookLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右看 (F) 的本地化字符串。
        /// </summary>
        public static string ThreeD_LookRightToolTip {
            get {
                return ResourceManager.GetString("ThreeD_LookRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上看 (A) 的本地化字符串。
        /// </summary>
        public static string ThreeD_LookUpToolTip {
            get {
                return ResourceManager.GetString("ThreeD_LookUpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型结构 的本地化字符串。
        /// </summary>
        public static string ThreeD_ModelStructure {
            get {
                return ResourceManager.GetString("ThreeD_ModelStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D模型查看器 的本地化字符串。
        /// </summary>
        public static string ThreeD_ModelViewer {
            get {
                return ResourceManager.GetString("ThreeD_ModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标 的本地化字符串。
        /// </summary>
        public static string ThreeD_Mouse {
            get {
                return ResourceManager.GetString("ThreeD_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 (B) 的本地化字符串。
        /// </summary>
        public static string ThreeD_MoveBackToolTip {
            get {
                return ResourceManager.GetString("ThreeD_MoveBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 (T) 的本地化字符串。
        /// </summary>
        public static string ThreeD_MoveForwardToolTip {
            get {
                return ResourceManager.GetString("ThreeD_MoveForwardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左移 (L) 的本地化字符串。
        /// </summary>
        public static string ThreeD_MoveLeftToolTip {
            get {
                return ResourceManager.GetString("ThreeD_MoveLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右移 (R) 的本地化字符串。
        /// </summary>
        public static string ThreeD_MoveRightToolTip {
            get {
                return ResourceManager.GetString("ThreeD_MoveRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模型 的本地化字符串。
        /// </summary>
        public static string ThreeD_OpenModel {
            get {
                return ResourceManager.GetString("ThreeD_OpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模型文件 的本地化字符串。
        /// </summary>
        public static string ThreeD_OpenModelToolTip {
            get {
                return ResourceManager.GetString("ThreeD_OpenModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正交投影 的本地化字符串。
        /// </summary>
        public static string ThreeD_Orthographic {
            get {
                return ResourceManager.GetString("ThreeD_Orthographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透视 的本地化字符串。
        /// </summary>
        public static string ThreeD_Perspective {
            get {
                return ResourceManager.GetString("ThreeD_Perspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预设视角 的本地化字符串。
        /// </summary>
        public static string ThreeD_PresetViews {
            get {
                return ResourceManager.GetString("ThreeD_PresetViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投影 的本地化字符串。
        /// </summary>
        public static string ThreeD_Projection {
            get {
                return ResourceManager.GetString("ThreeD_Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伪彩色 的本地化字符串。
        /// </summary>
        public static string ThreeD_PseudoColor {
            get {
                return ResourceManager.GetString("ThreeD_PseudoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染 的本地化字符串。
        /// </summary>
        public static string ThreeD_Rendering {
            get {
                return ResourceManager.GetString("ThreeD_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染设置 的本地化字符串。
        /// </summary>
        public static string ThreeD_RenderSettings {
            get {
                return ResourceManager.GetString("ThreeD_RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置视角 的本地化字符串。
        /// </summary>
        public static string ThreeD_ResetView {
            get {
                return ResourceManager.GetString("ThreeD_ResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置视角 (Home) 的本地化字符串。
        /// </summary>
        public static string ThreeD_ResetViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_ResetViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率 的本地化字符串。
        /// </summary>
        public static string ThreeD_Resolution {
            get {
                return ResourceManager.GetString("ThreeD_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复全部 的本地化字符串。
        /// </summary>
        public static string ThreeD_RestoreAll {
            get {
                return ResourceManager.GetString("ThreeD_RestoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        public static string ThreeD_Right {
            get {
                return ResourceManager.GetString("ThreeD_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_RightViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_RightViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        public static string ThreeD_Screenshot {
            get {
                return ResourceManager.GetString("ThreeD_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存当前3D视图为图片 的本地化字符串。
        /// </summary>
        public static string ThreeD_ScreenshotToolTip {
            get {
                return ResourceManager.GetString("ThreeD_ScreenshotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string ThreeD_Settings {
            get {
                return ResourceManager.GetString("ThreeD_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染分辨率设置 的本地化字符串。
        /// </summary>
        public static string ThreeD_SettingsToolTip {
            get {
                return ResourceManager.GetString("ThreeD_SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示材质 的本地化字符串。
        /// </summary>
        public static string ThreeD_ShowMaterial {
            get {
                return ResourceManager.GetString("ThreeD_ShowMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示贴图 的本地化字符串。
        /// </summary>
        public static string ThreeD_ShowTexture {
            get {
                return ResourceManager.GetString("ThreeD_ShowTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标分辨率 X: 的本地化字符串。
        /// </summary>
        public static string ThreeD_TargetResolutionX {
            get {
                return ResourceManager.GetString("ThreeD_TargetResolutionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标分辨率 Y: 的本地化字符串。
        /// </summary>
        public static string ThreeD_TargetResolutionY {
            get {
                return ResourceManager.GetString("ThreeD_TargetResolutionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        public static string ThreeD_Top {
            get {
                return ResourceManager.GetString("ThreeD_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_TopViewToolTip {
            get {
                return ResourceManager.GetString("ThreeD_TopViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string ThreeD_Value {
            get {
                return ResourceManager.GetString("ThreeD_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_View {
            get {
                return ResourceManager.GetString("ThreeD_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D视图 的本地化字符串。
        /// </summary>
        public static string ThreeD_View3D {
            get {
                return ResourceManager.GetString("ThreeD_View3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线框模式 的本地化字符串。
        /// </summary>
        public static string ThreeD_Wireframe {
            get {
                return ResourceManager.GetString("ThreeD_Wireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阈值处理 的本地化字符串。
        /// </summary>
        public static string ThresholdProcessing {
            get {
                return ResourceManager.GetString("ThresholdProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用后，打开 Gray32Float TIFF 时按当前图像最小值和最大值归一化后转换为 Gray16；关闭后保留原始 Gray32Float 图像。 的本地化字符串。
        /// </summary>
        public static string TifOpenConfig_ConvertToGray16_Description {
            get {
                return ResourceManager.GetString("TifOpenConfig_ConvertToGray16_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gray32Float 转为 Gray16 的本地化字符串。
        /// </summary>
        public static string TifOpenConfig_ConvertToGray16_DisplayName {
            get {
                return ResourceManager.GetString("TifOpenConfig_ConvertToGray16_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白平衡调整 的本地化字符串。
        /// </summary>
        public static string WhiteBalanceAdjustment {
            get {
                return ResourceManager.GetString("WhiteBalanceAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放工具 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适应屏幕 的本地化字符串。
        /// </summary>
        public static string ZoomUniform {
            get {
                return ResourceManager.GetString("ZoomUniform", resourceCulture);
            }
        }
    }
}
