#pragma warning disable

namespace ColorVision.Engine
{
    /// <summary>
    /// 算法结果类型枚举 - 定义支持的各种算法结果类型
    /// </summary>
    public enum ViewResultAlgType
    {
        None = -1,
        POI = 0,
        POI_XYZ = 1,
        POI_Y = 2,
        FOV = 3,
        SFR = 4,
        MTF = 5,
        Ghost = 6,
        LedCheck = 7,
        LightArea = 8,
        Distortion = 9,
        BuildPOI = 10,
        Compliance_Math = 11,
        Compliance_Math_CIE_XYZ = 12,
        Compliance_Math_CIE_Y = 13,
        Compliance_Contrast = 14,
        Compliance_Contrast_CIE_XYZ = 15,
        Compliance_Contrast_CIE_Y = 16,
        LEDStripDetection = 17,
        RealPOI = 18,
        DataLoad = 19,
        POI_Y_V2 = 20,
        OLED_FindDotsArrayMem = 21,
        OLED_FindDotsArrayMem_File = 22,
        POI_XYZ_File = 23,
        POI_Y_File = 24,
        POI_XYZ_V2 = 25,
        OLED_FindDotsArrayOutFile = 26,
        JND_CalVas = 27,
        POI_CAD_Mapping = 28,
        Image_Cropping = 29,
        Calibration = 30,
        POIReviseGen = 31,
        OLED_RebuildPixelsMem = 32,
        BuildPOI_File = 33,
        Compliance_Math_JND = 34,
        POI_CIE_File = 35,
        FindLightArea = 36,
        OLED_FindDotsArrayByCornerPts = 37,
        OLED_FindDotsArrayByCornerPts_File = 38,
        AOI = 39,
        ThirdPartyAlgorithms_File = 40,
        ThirdPartyAlgorithms_RealParam = 41,
        OLED_FindVHLine = 42,
        OLED_FindPixelDefectsForRebuildPicGrading = 43,
        OLED_FindPixelDefectsForRebuildPicGradingV2 = 243,
        OLED_FindMura = 44,
        OLED_AOI_ALL = 45,
        OLED_CombineQuaterImages = 46,
        OLED_FindPixelDefectsForRebuildPic = 47,
        OLED_FindPixelDefectsForQuardImg = 48,
        OLED_DetectBrightPixelsForBlackScreen = 49,
        KB = 50,
        KB_Raw = 51,
        KB_Output = 52,
        Compliance_Math_CIE_Y_Ex = 53,
        ARVR_BinocularFusion = 54,
        KB_Output_Lv = 55,
        KB_Output_CIE = 56,
        ARVR_SFR_FindROI = 60,
        ARVR_AAFindPoints = 61,
        PoiAnalysis = 62,
        FindCross = 63,
        Compliance_Judgment = 64,
        CompoundImg = 65,
        Math_DataConvert = 70,
        BlackMura_Calc = 80,
        OLEDAOI = 81,
        CalcEQE = 90,
        CaliAngleShift = 91,
        ImageROI = 92,
        ImageConvert = 93
    }
}
