//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStarkSemi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectStarkSemi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 应用滤波 的本地化字符串。
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方位角 的本地化字符串。
        /// </summary>
        public static string Azimuth {
            get {
                return ResourceManager.GetString("Azimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双边滤波 的本地化字符串。
        /// </summary>
        public static string BilateralFilter {
            get {
                return ResourceManager.GetString("BilateralFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正 的本地化字符串。
        /// </summary>
        public static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正状态 的本地化字符串。
        /// </summary>
        public static string CalibrationStatus {
            get {
                return ResourceManager.GetString("CalibrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取图像 的本地化字符串。
        /// </summary>
        public static string CaptureImage {
            get {
                return ResourceManager.GetString("CaptureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前型号 的本地化字符串。
        /// </summary>
        public static string CurrentModel {
            get {
                return ResourceManager.GetString("CurrentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滤波类型 的本地化字符串。
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高斯滤波 的本地化字符串。
        /// </summary>
        public static string GaussianFilter {
            get {
                return ResourceManager.GetString("GaussianFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像滤波 的本地化字符串。
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核大小 的本地化字符串。
        /// </summary>
        public static string KernelSize {
            get {
                return ResourceManager.GetString("KernelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低通滤波 的本地化字符串。
        /// </summary>
        public static string LowPassFilter {
            get {
                return ResourceManager.GetString("LowPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量相机状态 的本地化字符串。
        /// </summary>
        public static string MeasurementCameraStatus {
            get {
                return ResourceManager.GetString("MeasurementCameraStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中值滤波 的本地化字符串。
        /// </summary>
        public static string MedianFilter {
            get {
                return ResourceManager.GetString("MedianFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言(_Language) 的本地化字符串。
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 型号 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动平均 的本地化字符串。
        /// </summary>
        public static string MovingAverage {
            get {
                return ResourceManager.GetString("MovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无滤波 的本地化字符串。
        /// </summary>
        public static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未校正 的本地化字符串。
        /// </summary>
        public static string NotCalibrated {
            get {
                return ResourceManager.GetString("NotCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开 的本地化字符串。
        /// </summary>
        public static string NotOpened {
            get {
                return ResourceManager.GetString("NotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 观察相机状态 的本地化字符串。
        /// </summary>
        public static string ObservationCameraStatus {
            get {
                return ResourceManager.GetString("ObservationCameraStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开观察相机 的本地化字符串。
        /// </summary>
        public static string OpenObservationCamera {
            get {
                return ResourceManager.GetString("OpenObservationCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极角 的本地化字符串。
        /// </summary>
        public static string PolarAngle {
            get {
                return ResourceManager.GetString("PolarAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态信息 的本地化字符串。
        /// </summary>
        public static string StatusInformation {
            get {
                return ResourceManager.GetString("StatusInformation", resourceCulture);
            }
        }
    }
}
