//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.SocketProtocol.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.SocketProtocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 高级查询 的本地化字符串。
        /// </summary>
        public static string AdvancedQuery {
            get {
                return ResourceManager.GetString("AdvancedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动滚动 的本地化字符串。
        /// </summary>
        public static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空消息 的本地化字符串。
        /// </summary>
        public static string ClearMessages {
            get {
                return ResourceManager.GetString("ClearMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个客户端 的本地化字符串。
        /// </summary>
        public static string ClientCountFormat {
            get {
                return ResourceManager.GetString("ClientCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标客户端未连接 的本地化字符串。
        /// </summary>
        public static string ClientNotConnected {
            get {
                return ResourceManager.GetString("ClientNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信协议 的本地化字符串。
        /// </summary>
        public static string CommunicationProtocol {
            get {
                return ResourceManager.GetString("CommunicationProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接的客户端 的本地化字符串。
        /// </summary>
        public static string ConnectedClients {
            get {
                return ResourceManager.GetString("ConnectedClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        public static string ConnectionStatus {
            get {
                return ResourceManager.GetString("ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化复制 的本地化字符串。
        /// </summary>
        public static string CopyFormatted {
            get {
                return ResourceManager.GetString("CopyFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向 的本地化字符串。
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        public static string EnabledStatus {
            get {
                return ResourceManager.GetString("EnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件名 的本地化字符串。
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        public static string FilterReceived {
            get {
                return ResourceManager.GetString("FilterReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string FilterSent {
            get {
                return ResourceManager.GetString("FilterSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器启用状态 的本地化字符串。
        /// </summary>
        public static string IsServerEnabled {
            get {
                return ResourceManager.GetString("IsServerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听地址 的本地化字符串。
        /// </summary>
        public static string ListenAddress {
            get {
                return ResourceManager.GetString("ListenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地地址 的本地化字符串。
        /// </summary>
        public static string LocalEndPoint {
            get {
                return ResourceManager.GetString("LocalEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 条消息 的本地化字符串。
        /// </summary>
        public static string MessageCountFormat {
            get {
                return ResourceManager.GetString("MessageCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息详情 的本地化字符串。
        /// </summary>
        public static string MessageDetail {
            get {
                return ResourceManager.GetString("MessageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息日志 的本地化字符串。
        /// </summary>
        public static string MessageLog {
            get {
                return ResourceManager.GetString("MessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息设置 的本地化字符串。
        /// </summary>
        public static string MessageSettings {
            get {
                return ResourceManager.GetString("MessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据库 的本地化字符串。
        /// </summary>
        public static string OpenDatabase {
            get {
                return ResourceManager.GetString("OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string OpenDb {
            get {
                return ResourceManager.GetString("OpenDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开失败 的本地化字符串。
        /// </summary>
        public static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 {0} 失败: {1} 的本地化字符串。
        /// </summary>
        public static string OpenListenAddressFailedFormat {
            get {
                return ResourceManager.GetString("OpenListenAddressFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务打开 的本地化字符串。
        /// </summary>
        public static string OpenStatus {
            get {
                return ResourceManager.GetString("OpenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化查看 的本地化字符串。
        /// </summary>
        public static string PrettyPrintView {
            get {
                return ResourceManager.GetString("PrettyPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议 / 客户端 的本地化字符串。
        /// </summary>
        public static string ProtocolAndClients {
            get {
                return ResourceManager.GetString("ProtocolAndClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程地址 的本地化字符串。
        /// </summary>
        public static string RemoteEndPoint {
            get {
                return ResourceManager.GetString("RemoteEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重发 的本地化字符串。
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息重发失败: {0} 的本地化字符串。
        /// </summary>
        public static string ResendFailed {
            get {
                return ResourceManager.GetString("ResendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息重发成功 的本地化字符串。
        /// </summary>
        public static string ResendSuccess {
            get {
                return ResourceManager.GetString("ResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应码: 的本地化字符串。
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开 的本地化字符串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按客户端、事件名、MsgID、响应码或内容过滤 的本地化字符串。
        /// </summary>
        public static string SearchTooltip {
            get {
                return ResourceManager.GetString("SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        public static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务设置 的本地化字符串。
        /// </summary>
        public static string ServiceSettings {
            get {
                return ResourceManager.GetString("ServiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 消息 的本地化字符串。
        /// </summary>
        public static string Socket_MessageTable {
            get {
                return ResourceManager.GetString("Socket_MessageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询数量 的本地化字符串。
        /// </summary>
        public static string Socket_QueryCount {
            get {
                return ResourceManager.GetString("Socket_QueryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        public static string Socket_Receive {
            get {
                return ResourceManager.GetString("Socket_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Socket_Send {
            get {
                return ResourceManager.GetString("Socket_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按类型排序 的本地化字符串。
        /// </summary>
        public static string Socket_SortByType {
            get {
                return ResourceManager.GetString("Socket_SortByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 连接管理器 的本地化字符串。
        /// </summary>
        public static string SocketManagementWindow {
            get {
                return ResourceManager.GetString("SocketManagementWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 服务 的本地化字符串。
        /// </summary>
        public static string SocketServer {
            get {
                return ResourceManager.GetString("SocketServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 服务已连接 的本地化字符串。
        /// </summary>
        public static string SocketServerConnected {
            get {
                return ResourceManager.GetString("SocketServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket 服务未连接 的本地化字符串。
        /// </summary>
        public static string SocketServerDisconnected {
            get {
                return ResourceManager.GetString("SocketServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中 的本地化字符串。
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务 的本地化字符串。
        /// </summary>
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开 的本地化字符串。
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止中 的本地化字符串。
        /// </summary>
        public static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务失败: {0} 的本地化字符串。
        /// </summary>
        public static string StopServerFailedFormat {
            get {
                return ResourceManager.GetString("StopServerFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务 的本地化字符串。
        /// </summary>
        public static string StopService {
            get {
                return ResourceManager.GetString("StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        /// </summary>
        public static string UpdatedAtFormat {
            get {
                return ResourceManager.GetString("UpdatedAtFormat", resourceCulture);
            }
        }
    }
}
