//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventVWR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventVWR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 归档文件设置 的本地化字符串。
        /// </summary>
        public static string DumpFileSettings {
            get {
                return ResourceManager.GetString("DumpFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作需要使用管理员权限 的本地化字符串。
        /// </summary>
        public static string EventVWR_AdminRequired {
            get {
                return ResourceManager.GetString("EventVWR_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空Dmp 的本地化字符串。
        /// </summary>
        public static string EventVWR_ClearDmp {
            get {
                return ResourceManager.GetString("EventVWR_ClearDmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件详情 的本地化字符串。
        /// </summary>
        public static string EventVWR_EventDetail {
            get {
                return ResourceManager.GetString("EventVWR_EventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件列表 的本地化字符串。
        /// </summary>
        public static string EventVWR_EventList {
            get {
                return ResourceManager.GetString("EventVWR_EventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增强的异常管理,提供事件插件和Dump设置 的本地化字符串。
        /// </summary>
        public static string EventVWR_PluginDesc {
            get {
                return ResourceManager.GetString("EventVWR_PluginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件插件 的本地化字符串。
        /// </summary>
        public static string EventVWR_PluginName {
            get {
                return ResourceManager.GetString("EventVWR_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string EventVWR_Ready {
            get {
                return ResourceManager.GetString("EventVWR_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存Dmp 的本地化字符串。
        /// </summary>
        public static string EventVWR_SaveDmp {
            get {
                return ResourceManager.GetString("EventVWR_SaveDmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个事件以查看详情... 的本地化字符串。
        /// </summary>
        public static string EventVWR_SelectEvent {
            get {
                return ResourceManager.GetString("EventVWR_SelectEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string EventVWR_Source {
            get {
                return ResourceManager.GetString("EventVWR_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string EventVWR_Time {
            get {
                return ResourceManager.GetString("EventVWR_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件查看器 的本地化字符串。
        /// </summary>
        public static string EventVWR_Title {
            get {
                return ResourceManager.GetString("EventVWR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 事件查看器 的本地化字符串。
        /// </summary>
        public static string EventVWR_WinEvents {
            get {
                return ResourceManager.GetString("EventVWR_WinEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件查看器 的本地化字符串。
        /// </summary>
        public static string EventWindow {
            get {
                return ResourceManager.GetString("EventWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
    }
}
