//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        public static string Acquire {
            get {
                return ResourceManager.GetString("Acquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序关闭 的本地化字符串。
        /// </summary>
        public static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位 的本地化字符串。
        /// </summary>
        public static string Bit {
            get {
                return ResourceManager.GetString("Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlackMura检测 的本地化字符串。
        /// </summary>
        public static string BlackMuraDetect {
            get {
                return ResourceManager.GetString("BlackMuraDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建日期 的本地化字符串。
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变更日志 的本地化字符串。
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(旧) 的本地化字符串。
        /// </summary>
        public static string CheckUpdateOld {
            get {
                return ResourceManager.GetString("CheckUpdateOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件启动时检测更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &quot;清除安装包缓存 的本地化字符串。
        /// </summary>
        public static string ClearPackageCache {
            get {
                return ResourceManager.GetString("ClearPackageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorVision 更新程序 的本地化字符串。
        /// </summary>
        public static string ColorVisionUpdater {
            get {
                return ResourceManager.GetString("ColorVisionUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置结束 的本地化字符串。
        /// </summary>
        public static string ConfigurationComplete {
            get {
                return ResourceManager.GetString("ConfigurationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理窗口 的本地化字符串。
        /// </summary>
        public static string ConfigurationManagement {
            get {
                return ResourceManager.GetString("ConfigurationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否更新 的本地化字符串。
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前速度： 的本地化字符串。
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本已经是最新版本 的本地化字符串。
        /// </summary>
        public static string CurrentVersionIsUpToDate {
            get {
                return ResourceManager.GetString("CurrentVersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试中 的本地化字符串。
        /// </summary>
        public static string Debugging {
            get {
                return ResourceManager.GetString("Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载BeyondCompare 的本地化字符串。
        /// </summary>
        public static string DownLoadBeyondCompare {
            get {
                return ResourceManager.GetString("DownLoadBeyondCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载已取消 的本地化字符串。
        /// </summary>
        public static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地下载 的本地化字符串。
        /// </summary>
        public static string DownloadLocal {
            get {
                return ResourceManager.GetString("DownloadLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转储文件设置 的本地化字符串。
        /// </summary>
        public static string DumpFileSettings {
            get {
                return ResourceManager.GetString("DumpFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时 的本地化字符串。
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制更新 的本地化字符串。
        /// </summary>
        public static string ForceUpdate {
            get {
                return ResourceManager.GetString("ForceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化模块 的本地化字符串。
        /// </summary>
        public static string Initializer {
            get {
                return ResourceManager.GetString("Initializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键盘测试 的本地化字符串。
        /// </summary>
        public static string KBDetect {
            get {
                return ResourceManager.GetString("KBDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string LaunchSuccess {
            get {
                return ResourceManager.GetString("LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(_A) 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(_U) 的本地化字符串。
        /// </summary>
        public static string MenuUpdate {
            get {
                return ResourceManager.GetString("MenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReinstallCurrentVersion 的本地化字符串。
        /// </summary>
        public static string MenuUpdateReInstall_重新安装当前版本 {
            get {
                return ResourceManager.GetString("MenuUpdateReInstall_重新安装当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧边栏 的本地化字符串。
        /// </summary>
        public static string MenuViewSidebar {
            get {
                return ResourceManager.GetString("MenuViewSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态栏 的本地化字符串。
        /// </summary>
        public static string MenuViewStatusBar {
            get {
                return ResourceManager.GetString("MenuViewStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开BeyondCompare 的本地化字符串。
        /// </summary>
        public static string OpenBeyondCompare {
            get {
                return ResourceManager.GetString("OpenBeyondCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开缓存文件夹 的本地化字符串。
        /// </summary>
        public static string OpenCacheFolder {
            get {
                return ResourceManager.GetString("OpenCacheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配置文件夹 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolder {
            get {
                return ResourceManager.GetString("OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程 的本地化字符串。
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布日期 的本地化字符串。
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回退 的本地化字符串。
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回退软件需要先卸载在安装，或者是安装后重新运行安装包； 的本地化字符串。
        /// </summary>
        public static string RollbackRequiresUninstallThenInstallOrRerunPackage {
            get {
                return ResourceManager.GetString("RollbackRequiresUninstallThenInstallOrRerunPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置 的本地化字符串。
        /// </summary>
        public static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切面图 的本地化字符串。
        /// </summary>
        public static string SectionalDrawing {
            get {
                return ResourceManager.GetString("SectionalDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务协议 的本地化字符串。
        /// </summary>
        public static string ServiceAgreement {
            get {
                return ResourceManager.GetString("ServiceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置向导 的本地化字符串。
        /// </summary>
        public static string SetupWizard {
            get {
                return ResourceManager.GetString("SetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单通道 的本地化字符串。
        /// </summary>
        public static string singleChannel {
            get {
                return ResourceManager.GetString("singleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有未完成的配置，是否跳过 的本地化字符串。
        /// </summary>
        public static string SkipIncompleteConfigPrompt {
            get {
                return ResourceManager.GetString("SkipIncompleteConfigPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本 的本地化字符串。
        /// </summary>
        public static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本相同 的本地化字符串。
        /// </summary>
        public static string SoftwareVersionIdentical {
            get {
                return ResourceManager.GetString("SoftwareVersionIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复上次退出时窗口的大小和位置 的本地化字符串。
        /// </summary>
        public static string StartRecoverUILayout {
            get {
                return ResourceManager.GetString("StartRecoverUILayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 1 / 1 的本地化字符串。
        /// </summary>
        public static string Step11 {
            get {
                return ResourceManager.GetString("Step11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机启动(可能会不成功) 的本地化字符串。
        /// </summary>
        public static string TbSettingsStartBoot {
            get {
                return ResourceManager.GetString("TbSettingsStartBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三通道 的本地化字符串。
        /// </summary>
        public static string threeChannles {
            get {
                return ResourceManager.GetString("threeChannles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间： 的本地化字符串。
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度云盘下载 的本地化字符串。
        /// </summary>
        public static string UpdateBaidu {
            get {
                return ResourceManager.GetString("UpdateBaidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级 的本地化字符串。
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win10桌面经典菜单 的本地化字符串。
        /// </summary>
        public static string Win10ClassicDesktopMenu {
            get {
                return ResourceManager.GetString("Win10ClassicDesktopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向导 的本地化字符串。
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
    }
}
