//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许程序多开 的本地化字符串。
        /// </summary>
        public static string AllowMultipleInstances {
            get {
                return ResourceManager.GetString("AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许同时启动多个 ColorVision 实例。 的本地化字符串。
        /// </summary>
        public static string AllowMultipleInstancesDescription {
            get {
                return ResourceManager.GetString("AllowMultipleInstancesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序关闭 的本地化字符串。
        /// </summary>
        public static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位 的本地化字符串。
        /// </summary>
        public static string Bit {
            get {
                return ResourceManager.GetString("Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到更新记录 的本地化字符串。
        /// </summary>
        public static string CannotFindUpdateRecord {
            get {
                return ResourceManager.GetString("CannotFindUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变更日志 的本地化字符串。
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件启动时检测更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动软件时自动检测是否有可用更新。 的本地化字符串。
        /// </summary>
        public static string CheckUpdatesOnStartupDescription {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击是立即更新，点击否跳过该版本，点击取消稍后提醒 的本地化字符串。
        /// </summary>
        public static string ClickYesToUpdateNow {
            get {
                return ResourceManager.GetString("ClickYesToUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM 注册失败，请确认已授予管理员权限。 的本地化字符串。
        /// </summary>
        public static string ComRegistrationFailed {
            get {
                return ResourceManager.GetString("ComRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面宠物 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPet {
            get {
                return ResourceManager.GetString("ConfigDesktopPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 始终置顶 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetAlwaysOnTop {
            get {
                return ResourceManager.GetString("ConfigDesktopPetAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面宠物 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetCategory {
            get {
                return ResourceManager.GetString("ConfigDesktopPetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用待机提示 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetEnableIdleTips {
            get {
                return ResourceManager.GetString("ConfigDesktopPetEnableIdleTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待机提示间隔分钟 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetIdleTipInterval {
            get {
                return ResourceManager.GetString("ConfigDesktopPetIdleTipInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息显示秒数 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetMessageDisplaySeconds {
            get {
                return ResourceManager.GetString("ConfigDesktopPetMessageDisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宠物名称 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetName {
            get {
                return ResourceManager.GetString("ConfigDesktopPetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宠物透明度 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetOpacity {
            get {
                return ResourceManager.GetString("ConfigDesktopPetOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宠物缩放 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetScale {
            get {
                return ResourceManager.GetString("ConfigDesktopPetScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示消息通知 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetShowNotifications {
            get {
                return ResourceManager.GetString("ConfigDesktopPetShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动问候 的本地化字符串。
        /// </summary>
        public static string ConfigDesktopPetStartupGreeting {
            get {
                return ResourceManager.GetString("ConfigDesktopPetStartupGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用桌面宠物 的本地化字符串。
        /// </summary>
        public static string ConfigEnableDesktopPet {
            get {
                return ResourceManager.GetString("ConfigEnableDesktopPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示或隐藏桌面宠物组件。 的本地化字符串。
        /// </summary>
        public static string ConfigEnableDesktopPetDescription {
            get {
                return ResourceManager.GetString("ConfigEnableDesktopPetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 Live2D 渲染 的本地化字符串。
        /// </summary>
        public static string ConfigLive2DEnable {
            get {
                return ResourceManager.GetString("ConfigLive2DEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live2D 最大帧率 的本地化字符串。
        /// </summary>
        public static string ConfigLive2DMaxFps {
            get {
                return ResourceManager.GetString("ConfigLive2DMaxFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live2D 轻量动效 的本地化字符串。
        /// </summary>
        public static string ConfigLive2DMotionEffects {
            get {
                return ResourceManager.GetString("ConfigLive2DMotionEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live2D 模型或 HTML 路径 的本地化字符串。
        /// </summary>
        public static string ConfigLive2DPath {
            get {
                return ResourceManager.GetString("ConfigLive2DPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live2D 渲染分辨率 的本地化字符串。
        /// </summary>
        public static string ConfigLive2DRenderScale {
            get {
                return ResourceManager.GetString("ConfigLive2DRenderScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否更新 的本地化字符串。
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加上下文 的本地化字符串。
        /// </summary>
        public static string CopilotAddContext {
            get {
                return ResourceManager.GetString("CopilotAddContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件 的本地化字符串。
        /// </summary>
        public static string CopilotAddFile {
            get {
                return ResourceManager.GetString("CopilotAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + 添加模型 的本地化字符串。
        /// </summary>
        public static string CopilotAddModel {
            get {
                return ResourceManager.GetString("CopilotAddModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI 请求 的本地化字符串。
        /// </summary>
        public static string CopilotAiRequest {
            get {
                return ResourceManager.GetString("CopilotAiRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key 的本地化字符串。
        /// </summary>
        public static string CopilotApiKey {
            get {
                return ResourceManager.GetString("CopilotApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 AI 的本地化字符串。
        /// </summary>
        public static string CopilotAskAi {
            get {
                return ResourceManager.GetString("CopilotAskAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加到提问 的本地化字符串。
        /// </summary>
        public static string CopilotAttachToQuestion {
            get {
                return ResourceManager.GetString("CopilotAttachToQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起会话列表 的本地化字符串。
        /// </summary>
        public static string CopilotCollapseConversationList {
            get {
                return ResourceManager.GetString("CopilotCollapseConversationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 Copilot 的本地化字符串。
        /// </summary>
        public static string CopilotConfigureCopilot {
            get {
                return ResourceManager.GetString("CopilotConfigureCopilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先点右上角配置添加模型，再开始对话。 的本地化字符串。
        /// </summary>
        public static string CopilotConfigureModelFirst {
            get {
                return ResourceManager.GetString("CopilotConfigureModelFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话 的本地化字符串。
        /// </summary>
        public static string CopilotConversations {
            get {
                return ResourceManager.GetString("CopilotConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制详情 的本地化字符串。
        /// </summary>
        public static string CopilotCopyDetails {
            get {
                return ResourceManager.GetString("CopilotCopyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制当前消息 的本地化字符串。
        /// </summary>
        public static string CopilotCopyMessage {
            get {
                return ResourceManager.GetString("CopilotCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口上下文 的本地化字符串。
        /// </summary>
        public static string CopilotCurrentWindowContext {
            get {
                return ResourceManager.GetString("CopilotCurrentWindowContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常详情 的本地化字符串。
        /// </summary>
        public static string CopilotExceptionDetails {
            get {
                return ResourceManager.GetString("CopilotExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常诊断 的本地化字符串。
        /// </summary>
        public static string CopilotExceptionDiagnosis {
            get {
                return ResourceManager.GetString("CopilotExceptionDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 Agent 的本地化字符串。
        /// </summary>
        public static string CopilotExecuteAgent {
            get {
                return ResourceManager.GetString("CopilotExecuteAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开会话列表 的本地化字符串。
        /// </summary>
        public static string CopilotExpandConversationList {
            get {
                return ResourceManager.GetString("CopilotExpandConversationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google 搜索 的本地化字符串。
        /// </summary>
        public static string CopilotGoogleSearch {
            get {
                return ResourceManager.GetString("CopilotGoogleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言模型 的本地化字符串。
        /// </summary>
        public static string CopilotLanguageModel {
            get {
                return ResourceManager.GetString("CopilotLanguageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string CopilotLines {
            get {
                return ResourceManager.GetString("CopilotLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大 Token 的本地化字符串。
        /// </summary>
        public static string CopilotMaxToken {
            get {
                return ResourceManager.GetString("CopilotMaxToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型 的本地化字符串。
        /// </summary>
        public static string CopilotModel {
            get {
                return ResourceManager.GetString("CopilotModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string CopilotName {
            get {
                return ResourceManager.GetString("CopilotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新会话 的本地化字符串。
        /// </summary>
        public static string CopilotNewConversation {
            get {
                return ResourceManager.GetString("CopilotNewConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴图片 的本地化字符串。
        /// </summary>
        public static string CopilotPasteImage {
            get {
                return ResourceManager.GetString("CopilotPasteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议 的本地化字符串。
        /// </summary>
        public static string CopilotProtocol {
            get {
                return ResourceManager.GetString("CopilotProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近日志 的本地化字符串。
        /// </summary>
        public static string CopilotRecentLogs {
            get {
                return ResourceManager.GetString("CopilotRecentLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近 N 行 的本地化字符串。
        /// </summary>
        public static string CopilotRecentNLines {
            get {
                return ResourceManager.GetString("CopilotRecentNLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新日志 的本地化字符串。
        /// </summary>
        public static string CopilotRefreshLog {
            get {
                return ResourceManager.GetString("CopilotRefreshLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新抓取网页上下文并生成回答 的本地化字符串。
        /// </summary>
        public static string CopilotRefreshWebContext {
            get {
                return ResourceManager.GetString("CopilotRefreshWebContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新生成当前轮回答 的本地化字符串。
        /// </summary>
        public static string CopilotRegenerateAnswer {
            get {
                return ResourceManager.GetString("CopilotRegenerateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        public static string CopilotRetry {
            get {
                return ResourceManager.GetString("CopilotRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从右侧选择历史会话，或点击 + 新建会话。 的本地化字符串。
        /// </summary>
        public static string CopilotSelectHistoryOrNew {
            get {
                return ResourceManager.GetString("CopilotSelectHistoryOrNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string CopilotSend {
            get {
                return ResourceManager.GetString("CopilotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定网页 的本地化字符串。
        /// </summary>
        public static string CopilotSpecifyWebPage {
            get {
                return ResourceManager.GetString("CopilotSpecifyWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止生成 的本地化字符串。
        /// </summary>
        public static string CopilotStopGeneration {
            get {
                return ResourceManager.GetString("CopilotStopGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义提示词 的本地化字符串。
        /// </summary>
        public static string CopilotSystemPrompt {
            get {
                return ResourceManager.GetString("CopilotSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        public static string CopilotTemperature {
            get {
                return ResourceManager.GetString("CopilotTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日日志 的本地化字符串。
        /// </summary>
        public static string CopilotTodayLog {
            get {
                return ResourceManager.GetString("CopilotTodayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具轮次 的本地化字符串。
        /// </summary>
        public static string CopilotToolRounds {
            get {
                return ResourceManager.GetString("CopilotToolRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorVision 捕获到未处理异常 的本地化字符串。
        /// </summary>
        public static string CopilotUnhandledException {
            get {
                return ResourceManager.GetString("CopilotUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新快照 的本地化字符串。
        /// </summary>
        public static string CopilotUpdateSnapshot {
            get {
                return ResourceManager.GetString("CopilotUpdateSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂商 的本地化字符串。
        /// </summary>
        public static string CopilotVendor {
            get {
                return ResourceManager.GetString("CopilotVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新前创建程序快照 的本地化字符串。
        /// </summary>
        public static string CreateSnapshotBeforeUpdate {
            get {
                return ResourceManager.GetString("CreateSnapshotBeforeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后，主程序、插件或组合更新前都会创建一次完整程序快照，可能延长更新时间。 的本地化字符串。
        /// </summary>
        public static string CreateSnapshotBeforeUpdateDescription {
            get {
                return ResourceManager.GetString("CreateSnapshotBeforeUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本已经是最新版本 的本地化字符串。
        /// </summary>
        public static string CurrentVersionIsUpToDate {
            get {
                return ResourceManager.GetString("CurrentVersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试中 的本地化字符串。
        /// </summary>
        public static string Debugging {
            get {
                return ResourceManager.GetString("Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 始终置顶 的本地化字符串。
        /// </summary>
        public static string DesktopPetAlwaysOnTop {
            get {
                return ResourceManager.GetString("DesktopPetAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        public static string DesktopPetExit {
            get {
                return ResourceManager.GetString("DesktopPetExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏桌宠 的本地化字符串。
        /// </summary>
        public static string DesktopPetHide {
            get {
                return ResourceManager.GetString("DesktopPetHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我在这儿，有消息会提醒你。 的本地化字符串。
        /// </summary>
        public static string DesktopPetIdleTip1 {
            get {
                return ResourceManager.GetString("DesktopPetIdleTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休息一下眼睛，顺手保存当前工作。 的本地化字符串。
        /// </summary>
        public static string DesktopPetIdleTip2 {
            get {
                return ResourceManager.GetString("DesktopPetIdleTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要我安静一点，可以右键把通知关掉。 的本地化字符串。
        /// </summary>
        public static string DesktopPetIdleTip3 {
            get {
                return ResourceManager.GetString("DesktopPetIdleTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有本地 Live2D 模型的话，可以在设置里接进来。 的本地化字符串。
        /// </summary>
        public static string DesktopPetIdleTip4 {
            get {
                return ResourceManager.GetString("DesktopPetIdleTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面宠物 的本地化字符串。
        /// </summary>
        public static string DesktopPetInitializerName {
            get {
                return ResourceManager.GetString("DesktopPetInitializerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型加载失败，已切换为内置形象。 的本地化字符串。
        /// </summary>
        public static string DesktopPetLive2DError {
            get {
                return ResourceManager.GetString("DesktopPetLive2DError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型加载失败：{0} 的本地化字符串。
        /// </summary>
        public static string DesktopPetLive2DErrorDetail {
            get {
                return ResourceManager.GetString("DesktopPetLive2DErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌宠提醒 的本地化字符串。
        /// </summary>
        public static string DesktopPetReminder {
            get {
                return ResourceManager.GetString("DesktopPetReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送测试提醒 的本地化字符串。
        /// </summary>
        public static string DesktopPetSendTestReminder {
            get {
                return ResourceManager.GetString("DesktopPetSendTestReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌宠设置 的本地化字符串。
        /// </summary>
        public static string DesktopPetSettings {
            get {
                return ResourceManager.GetString("DesktopPetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面宠物设置 的本地化字符串。
        /// </summary>
        public static string DesktopPetSettingsTitle {
            get {
                return ResourceManager.GetString("DesktopPetSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示主窗口 的本地化字符串。
        /// </summary>
        public static string DesktopPetShowMainWindow {
            get {
                return ResourceManager.GetString("DesktopPetShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示通知 的本地化字符串。
        /// </summary>
        public static string DesktopPetShowNotifications {
            get {
                return ResourceManager.GetString("DesktopPetShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorVision 已启动，我会在这里提醒你。 的本地化字符串。
        /// </summary>
        public static string DesktopPetStartupGreeting {
            get {
                return ResourceManager.GetString("DesktopPetStartupGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一条来自桌宠的测试消息。 的本地化字符串。
        /// </summary>
        public static string DesktopPetTestMessage {
            get {
                return ResourceManager.GetString("DesktopPetTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备控制 的本地化字符串。
        /// </summary>
        public static string DeviceControl {
            get {
                return ResourceManager.GetString("DeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不使用系统代理 的本地化字符串。
        /// </summary>
        public static string DisableSystemProxyForUpdates {
            get {
                return ResourceManager.GetString("DisableSystemProxyForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后，更新检查和插件市场请求将直接连接公网服务；关闭时使用 Windows 系统代理。修改后从下一次请求生效。 的本地化字符串。
        /// </summary>
        public static string DisableSystemProxyForUpdatesDescription {
            get {
                return ResourceManager.GetString("DisableSystemProxyForUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地下载 的本地化字符串。
        /// </summary>
        public static string DownloadLocal {
            get {
                return ResourceManager.GetString("DownloadLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制更新 的本地化字符串。
        /// </summary>
        public static string ForceUpdate {
            get {
                return ResourceManager.GetString("ForceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化模块 的本地化字符串。
        /// </summary>
        public static string Initializer {
            get {
                return ResourceManager.GetString("Initializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string LaunchSuccess {
            get {
                return ResourceManager.GetString("LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(_A) 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件关联 的本地化字符串。
        /// </summary>
        public static string MenuFileAssociation {
            get {
                return ResourceManager.GetString("MenuFileAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册缩略图预览 的本地化字符串。
        /// </summary>
        public static string MenuRegisterThumbnail {
            get {
                return ResourceManager.GetString("MenuRegisterThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载缩略图预览 的本地化字符串。
        /// </summary>
        public static string MenuUnregisterThumbnail {
            get {
                return ResourceManager.GetString("MenuUnregisterThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态栏 的本地化字符串。
        /// </summary>
        public static string MenuViewStatusBar {
            get {
                return ResourceManager.GetString("MenuViewStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认打开 的本地化字符串。
        /// </summary>
        public static string OpenWithSystemDefault {
            get {
                return ResourceManager.GetString("OpenWithSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到软件上次没有成功打开，是否禁用插件 的本地化字符串。
        /// </summary>
        public static string PluginLoadFailedPrompt {
            get {
                return ResourceManager.GetString("PluginLoadFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取更新记录失败: {0} 的本地化字符串。
        /// </summary>
        public static string ReadUpdateRecordFailed {
            get {
                return ResourceManager.GetString("ReadUpdateRecordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速搜索本机文件和文件夹。 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareEverythingDescription {
            get {
                return ResourceManager.GetString("RecommendedSoftwareEverythingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已安装 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareInstalled {
            get {
                return ResourceManager.GetString("RecommendedSoftwareInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装包缺失 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwarePackageMissing {
            get {
                return ResourceManager.GetString("RecommendedSoftwarePackageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将安装 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareSelected {
            get {
                return ResourceManager.GetString("RecommendedSoftwareSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已跳过 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareSkipped {
            get {
                return ResourceManager.GetString("RecommendedSoftwareSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看、解压和创建常用压缩文件。 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWinRarDescription {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWinRarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认选择 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardConfirmAction {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议安装 Everything 和 WinRAR。未安装的软件已默认勾选；单击“下一步”或“安装所选软件”会依次打开安装程序。取消勾选即可跳过，不影响继续使用 ColorVision。 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardDescription {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐软件 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardHeader {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装所选软件 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardInstallAction {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardInstallAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 安装程序启动失败：{1} 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardInstallErrorFormat {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardInstallErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 尚未安装完成。请重试，或取消勾选后继续。 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardInstallIncompleteFormat {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardInstallIncompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 {0} 安装包：{1} 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardPackageMissingFormat {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardPackageMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新检查 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardRecheckAction {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardRecheckAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装... 的本地化字符串。
        /// </summary>
        public static string RecommendedSoftwareWizardWorkingAction {
            get {
                return ResourceManager.GetString("RecommendedSoftwareWizardWorkingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败：{0} 的本地化字符串。
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册表应用成功 的本地化字符串。
        /// </summary>
        public static string RegistryAppliedSuccess {
            get {
                return ResourceManager.GetString("RegistryAppliedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布日期 的本地化字符串。
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回退 的本地化字符串。
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查 ColorVision Service Host 的安装和运行状态。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardChecking {
            get {
                return ResourceManager.GetString("ServiceHostWizardChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorVision 后台服务 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardHeader {
            get {
                return ResourceManager.GetString("ServiceHostWizardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装后台服务 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardInstallAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardInstallAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务管理器依赖 ColorVision Service Host 执行需要管理员权限的安装和维护操作。点击“安装后台服务”后，Windows 会请求一次管理员授权。
        ///
        ///安装包：{0} 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardNotInstalledFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardNotInstalledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台服务安装包不存在：{0} 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardPackageMissingFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardPackageMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台服务已安装并正常运行（版本 {0}）。
        ///
        ///服务管理器现在可以安全地安装、更新和控制本机服务。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardReadyFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardReadyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新检查 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardRecheckAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardRecheckAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复并启动 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardRepairAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardRepairAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardRetryAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardRetryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法确认后台服务状态，请重试。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardStatusUnknown {
            get {
                return ResourceManager.GetString("ServiceHostWizardStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台服务已安装（版本 {0}），但当前没有运行。请修复并启动后再继续。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardStoppedFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用的后台服务安装包，因此无法继续初始化。
        ///
        ///安装包：{0} 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardUnavailableFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardUnavailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新后台服务 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardUpdateAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardUpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台服务需要更新或修复。当前版本：{0}；安装包版本：{1}。完成后才能进入服务管理器。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardUpdateFormat {
            get {
                return ResourceManager.GetString("ServiceHostWizardUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备 ColorVision Service Host。安装或修复时可能会请求管理员权限，请完成系统提示。 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardWorking {
            get {
                return ResourceManager.GetString("ServiceHostWizardWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理… 的本地化字符串。
        /// </summary>
        public static string ServiceHostWizardWorkingAction {
            get {
                return ResourceManager.GetString("ServiceHostWizardWorkingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 Shell Extension:\n{0} 的本地化字符串。
        /// </summary>
        public static string ShellExtensionNotFound {
            get {
                return ResourceManager.GetString("ShellExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本相同 的本地化字符串。
        /// </summary>
        public static string SoftwareVersionIdentical {
            get {
                return ResourceManager.GetString("SoftwareVersionIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案资源管理器 的本地化字符串。
        /// </summary>
        public static string SolutionExplorer {
            get {
                return ResourceManager.GetString("SolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机启动(可能会不成功) 的本地化字符串。
        /// </summary>
        public static string TbSettingsStartBoot {
            get {
                return ResourceManager.GetString("TbSettingsStartBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止未响应的进程 的本地化字符串。
        /// </summary>
        public static string TerminateUnresponsiveProcess {
            get {
                return ResourceManager.GetString("TerminateUnresponsiveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图预览注册成功！\n重启资源管理器后，.cvraw 和 .cvcie 文件将显示图像缩略图。 的本地化字符串。
        /// </summary>
        public static string ThumbnailRegistrationSuccess {
            get {
                return ResourceManager.GetString("ThumbnailRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图预览已卸载。 的本地化字符串。
        /// </summary>
        public static string ThumbnailUnregistered {
            get {
                return ResourceManager.GetString("ThumbnailUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载失败：{0} 的本地化字符串。
        /// </summary>
        public static string UnregistrationFailed {
            get {
                return ResourceManager.GetString("UnregistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的文件格式 的本地化字符串。
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含兼容性与稳定性更新。 的本地化字符串。
        /// </summary>
        public static string UpdateCompatibilityStability {
            get {
                return ResourceManager.GetString("UpdateCompatibilityStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已是最新版本 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewAlreadyLatestHeading {
            get {
                return ResourceManager.GetString("UpdatePreviewAlreadyLatestHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将下载完整安装包并沿用当前主程序更新流程。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationCardSummaryFull {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationCardSummaryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将应用 {0} 个主程序增量包，并与所选更新一起完成本轮更新。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationCardSummaryIncrementalFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationCardSummaryIncrementalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整主程序安装包 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationFullPackageLabel {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationFullPackageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主程序增量 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationIncrementalCategory {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationIncrementalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个增量更新包 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationIncrementalPackagesFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationIncrementalPackagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序备份 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationSnapshotsLink {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationSnapshotsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主程序更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationUpdateCategory {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整安装包 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationUpdateModeFull {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationUpdateModeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增量更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationUpdateModeIncremental {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationUpdateModeIncremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新方式 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewApplicationUpdateModeLabel {
            get {
                return ResourceManager.GetString("UpdatePreviewApplicationUpdateModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewCancelButtonText {
            get {
                return ResourceManager.GetString("UpdatePreviewCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewCheckingHeading {
            get {
                return ResourceManager.GetString("UpdatePreviewCheckingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取主程序、插件和主题的最新版本信息，请稍候。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewCheckingSummary {
            get {
                return ResourceManager.GetString("UpdatePreviewCheckingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewCloseButtonText {
            get {
                return ResourceManager.GetString("UpdatePreviewCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现 {0} 个可用更新，可按需选择后立即安装。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewDialogSummaryDefault {
            get {
                return ResourceManager.GetString("UpdatePreviewDialogSummaryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前主程序、插件和主题均无需更新。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewDialogSummaryNoUpdates {
            get {
                return ResourceManager.GetString("UpdatePreviewDialogSummaryNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另有 {0} 个更新因兼容性要求未显示。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewDialogSummarySkippedCount {
            get {
                return ResourceManager.GetString("UpdatePreviewDialogSummarySkippedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现 {0} 个可用更新，包含{1}。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewDialogSummaryWithKinds {
            get {
                return ResourceManager.GetString("UpdatePreviewDialogSummaryWithKinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewFoundUpdatesHeading {
            get {
                return ResourceManager.GetString("UpdatePreviewFoundUpdatesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个主程序更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewHeaderApplicationCount {
            get {
                return ResourceManager.GetString("UpdatePreviewHeaderApplicationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个插件更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewHeaderPluginCount {
            get {
                return ResourceManager.GetString("UpdatePreviewHeaderPluginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宿主要求：{0} 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewHostRequirementFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewHostRequirementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主程序版本 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewHostVersionLabel {
            get {
                return ResourceManager.GetString("UpdatePreviewHostVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewLaterButtonText {
            get {
                return ResourceManager.GetString("UpdatePreviewLaterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未发现需要安装的更新项。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewNoInstallableUpdatesMessage {
            get {
                return ResourceManager.GetString("UpdatePreviewNoInstallableUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可更新的插件。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewNoPluginUpdates {
            get {
                return ResourceManager.GetString("UpdatePreviewNoPluginUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前主程序、插件和主题均无需更新。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewNoUpdatesMessage {
            get {
                return ResourceManager.GetString("UpdatePreviewNoUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有可用更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewNoUpdatesTitle {
            get {
                return ResourceManager.GetString("UpdatePreviewNoUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新包下载失败，请稍后重试。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewPackageDownloadFailed {
            get {
                return ResourceManager.GetString("UpdatePreviewPackageDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整安装包更新时，本轮不合并插件更新。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewPluginDeferredByFullApplicationUpdate {
            get {
                return ResourceManager.GetString("UpdatePreviewPluginDeferredByFullApplicationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件下载未成功完成，请稍后重试。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewPluginDownloadFailed {
            get {
                return ResourceManager.GetString("UpdatePreviewPluginDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewPluginUpdateCategory {
            get {
                return ResourceManager.GetString("UpdatePreviewPluginUpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必选 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewRequiredBadge {
            get {
                return ResourceManager.GetString("UpdatePreviewRequiredBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在扫描可用更新项 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewScanningTitle {
            get {
                return ResourceManager.GetString("UpdatePreviewScanningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新前创建程序快照 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionCreatesSnapshot {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionCreatesSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本轮不合并插件更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionDefersPluginUpdates {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionDefersPluginUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含必选更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionIncludesRequired {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionIncludesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新完成后将重启应用 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionRestartRequired {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择 {0} / {1} 个插件 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionSelectedPluginsFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionSelectedPluginsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择 {0} / {1} 个可选更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSelectionSelectedUpdatesFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewSelectionSelectedUpdatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前主程序和插件都已经是最新版本。 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewShowNoUpdatesLatestMessage {
            get {
                return ResourceManager.GetString("UpdatePreviewShowNoUpdatesLatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有可执行的联合更新。以下插件因兼容性要求被跳过：{0} 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewShowNoUpdatesSkippedMessage {
            get {
                return ResourceManager.GetString("UpdatePreviewShowNoUpdatesSkippedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下更新因兼容性要求未显示：{0} 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewSkippedIncompatibleUpdatesFormat {
            get {
                return ResourceManager.GetString("UpdatePreviewSkippedIncompatibleUpdatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewUnknownVersion {
            get {
                return ResourceManager.GetString("UpdatePreviewUnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主程序 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewUpdateKindApplication {
            get {
                return ResourceManager.GetString("UpdatePreviewUpdateKindApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewUpdateKindPlugin {
            get {
                return ResourceManager.GetString("UpdatePreviewUpdateKindPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即更新 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewUpdateNowButtonText {
            get {
                return ResourceManager.GetString("UpdatePreviewUpdateNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在更新... 的本地化字符串。
        /// </summary>
        public static string UpdatePreviewUpdatingButtonText {
            get {
                return ResourceManager.GetString("UpdatePreviewUpdatingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未命名插件 的本地化字符串。
        /// </summary>
        public static string UpdateUnnamedPlugin {
            get {
                return ResourceManager.GetString("UpdateUnnamedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win10桌面经典菜单 的本地化字符串。
        /// </summary>
        public static string Win10ClassicDesktopMenu {
            get {
                return ResourceManager.GetString("Win10ClassicDesktopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在支持的系统上使用经典桌面右键菜单。 的本地化字符串。
        /// </summary>
        public static string Win10ClassicDesktopMenuDescription {
            get {
                return ResourceManager.GetString("Win10ClassicDesktopMenuDescription", resourceCulture);
            }
        }
    }
}
