//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServicePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsServicePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 激活Windows 的本地化字符串。
        /// </summary>
        public static string ActivateWindows {
            get {
                return ResourceManager.GetString("ActivateWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到BCompare，是否下载 的本地化字符串。
        /// </summary>
        public static string BCompareNotFound_DownloadPrompt {
            get {
                return ResourceManager.GetString("BCompareNotFound_DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机日志 的本地化字符串。
        /// </summary>
        public static string CameraLog {
            get {
                return ResourceManager.GetString("CameraLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载BeyondCompare 的本地化字符串。
        /// </summary>
        public static string DownLoadBeyondCompare {
            get {
                return ResourceManager.GetString("DownLoadBeyondCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转储文件设置 的本地化字符串。
        /// </summary>
        public static string DumpFileSettings {
            get {
                return ResourceManager.GetString("DumpFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装MQTT 的本地化字符串。
        /// </summary>
        public static string InstallMqtt {
            get {
                return ResourceManager.GetString("InstallMqtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理服务 的本地化字符串。
        /// </summary>
        public static string ManagementService {
            get {
                return ResourceManager.GetString("ManagementService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开BeyondCompare 的本地化字符串。
        /// </summary>
        public static string OpenBeyondCompare {
            get {
                return ResourceManager.GetString("OpenBeyondCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RC服务日志 的本地化字符串。
        /// </summary>
        public static string RCServiceLog {
            get {
                return ResourceManager.GetString("RCServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 的本地化字符串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务日志 的本地化字符串。
        /// </summary>
        public static string ServiceLog {
            get {
                return ResourceManager.GetString("ServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱仪日志 的本地化字符串。
        /// </summary>
        public static string SpectrometerLog {
            get {
                return ResourceManager.GetString("SpectrometerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 x64服务日志 的本地化字符串。
        /// </summary>
        public static string x64ServiceLog {
            get {
                return ResourceManager.GetString("x64ServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 x86服务日志 的本地化字符串。
        /// </summary>
        public static string x86ServiceLog {
            get {
                return ResourceManager.GetString("x86ServiceLog", resourceCulture);
            }
        }
    }
}
