//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVision.Solution.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVision.Solution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号登录 的本地化字符串。
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建下载 的本地化字符串。
        /// </summary>
        public static string AddDownload {
            get {
                return ResourceManager.GetString("AddDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消下载 的本地化字符串。
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除缓存 的本地化字符串。
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除记录 的本地化字符串。
        /// </summary>
        public static string ClearRecords {
            get {
                return ResourceManager.GetString("ClearRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清除所有下载记录吗？ 的本地化字符串。
        /// </summary>
        public static string ClearRecordsConfirm {
            get {
                return ResourceManager.GetString("ClearRecordsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置新工程 的本地化字符串。
        /// </summary>
        public static string ConfigureNewProject {
            get {
                return ResourceManager.GetString("ConfigureNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制完整路径 的本地化字符串。
        /// </summary>
        public static string CopyFullPath {
            get {
                return ResourceManager.GetString("CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制路径 的本地化字符串。
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制下载链接 的本地化字符串。
        /// </summary>
        public static string CopyUrl {
            get {
                return ResourceManager.GetString("CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册一个 的本地化字符串。
        /// </summary>
        public static string Create_an_account {
            get {
                return ResourceManager.GetString("Create_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建一个新的的项目或文件 的本地化字符串。
        /// </summary>
        public static string CreateNewProjectOrFile {
            get {
                return ResourceManager.GetString("CreateNewProjectOrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建工程 的本地化字符串。
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreateTimeHeader {
            get {
                return ResourceManager.GetString("CreateTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认导出存储格式 的本地化字符串。
        /// </summary>
        public static string DefaultExportStorageFormat {
            get {
                return ResourceManager.GetString("DefaultExportStorageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除记录 的本地化字符串。
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中 的本地化字符串。
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载中 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载管理器 的本地化字符串。
        /// </summary>
        public static string DownloadManager {
            get {
                return ResourceManager.GetString("DownloadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载链接: 的本地化字符串。
        /// </summary>
        public static string DownloadUrl {
            get {
                return ResourceManager.GetString("DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑信息 的本地化字符串。
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑解决方案 的本地化字符串。
        /// </summary>
        public static string EditSolution {
            get {
                return ResourceManager.GetString("EditSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已删除 的本地化字符串。
        /// </summary>
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        public static string DownloadCompletedMessage {
            get {
                return ResourceManager.GetString("DownloadCompletedMessage", resourceCulture);
            }
        }
        
        public static string DownloadFailedMessage {
            get {
                return ResourceManager.GetString("DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入账号 的本地化字符串。
        /// </summary>
        public static string FillAccount {
            get {
                return ResourceManager.GetString("FillAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 及其所有内容讲永久删除。 的本地化字符串。
        /// </summary>
        public static string FolderDeleteSign {
            get {
                return ResourceManager.GetString("FolderDeleteSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录/切换 的本地化字符串。
        /// </summary>
        public static string LoginOrSwitch {
            get {
                return ResourceManager.GetString("LoginOrSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录时间 的本地化字符串。
        /// </summary>
        public static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加(_D) 的本地化字符串。
        /// </summary>
        public static string MenuAdd {
            get {
                return ResourceManager.GetString("MenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制完整路径(_U) 的本地化字符串。
        /// </summary>
        public static string MenuCopyFullPath {
            get {
                return ResourceManager.GetString("MenuCopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所在的文件夹(_O) 的本地化字符串。
        /// </summary>
        public static string MenuOpenContainingFolder {
            get {
                return ResourceManager.GetString("MenuOpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在文件管理器中打开文件夹(_X) 的本地化字符串。
        /// </summary>
        public static string MenuOpenFileInExplorer {
            get {
                return ResourceManager.GetString("MenuOpenFileInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性(_R) 的本地化字符串。
        /// </summary>
        public static string MenuProperty {
            get {
                return ResourceManager.GetString("MenuProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建工程格式 的本地化字符串。
        /// </summary>
        public static string NewProjectFormat {
            get {
                return ResourceManager.GetString("NewProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建工程 的本地化字符串。
        /// </summary>
        public static string NewSolution {
            get {
                return ResourceManager.GetString("NewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有账户？ 的本地化字符串。
        /// </summary>
        public static string NoAccountYet {
            get {
                return ResourceManager.GetString("NoAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到 的本地化字符串。
        /// </summary>
        public static string NoFound {
            get {
                return ResourceManager.GetString("NoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到相关项目 的本地化字符串。
        /// </summary>
        public static string NoRelatedItemsFound {
            get {
                return ResourceManager.GetString("NoRelatedItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开下载目录 的本地化字符串。
        /// </summary>
        public static string OpenDownloadFolder {
            get {
                return ResourceManager.GetString("OpenDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所在文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开项目 的本地化字符串。
        /// </summary>
        public static string OpenItem {
            get {
                return ResourceManager.GetString("OpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开本地的项目或文件 的本地化字符串。
        /// </summary>
        public static string OpenLocalProjectOrFile {
            get {
                return ResourceManager.GetString("OpenLocalProjectOrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开工程 的本地化字符串。
        /// </summary>
        public static string OpenSolution {
            get {
                return ResourceManager.GetString("OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页: 的本地化字符串。
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string PermissionManagement {
            get {
                return ResourceManager.GetString("PermissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限模式 的本地化字符串。
        /// </summary>
        public static string PermissionMode {
            get {
                return ResourceManager.GetString("PermissionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程 的本地化字符串。
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程设置 的本地化字符串。
        /// </summary>
        public static string ProjectSettings {
            get {
                return ResourceManager.GetString("ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近使用过的文件(_F) 的本地化字符串。
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近使用的内容 的本地化字符串。
        /// </summary>
        public static string RecentUsedContent {
            get {
                return ResourceManager.GetString("RecentUsedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关项目 的本地化字符串。
        /// </summary>
        public static string RelateItem {
            get {
                return ResourceManager.GetString("RelateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住登录状态（7天内自动登录） 的本地化字符串。
        /// </summary>
        public static string RememberLoginStatus7Days {
            get {
                return ResourceManager.GetString("RememberLoginStatus7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已重置 的本地化字符串。
        /// </summary>
        public static string Reseted {
            get {
                return ResourceManager.GetString("Reseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试下载 的本地化字符串。
        /// </summary>
        public static string RetryDownload {
            get {
                return ResourceManager.GetString("RetryDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色列表 的本地化字符串。
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存目录: 的本地化字符串。
        /// </summary>
        public static string SaveDirectory {
            get {
                return ResourceManager.GetString("SaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索工程文件 的本地化字符串。
        /// </summary>
        public static string SearchProjectFiles {
            get {
                return ResourceManager.GetString("SearchProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择项目保存位置 的本地化字符串。
        /// </summary>
        public static string SelectProjectSaveLocation {
            get {
                return ResourceManager.GetString("SelectProjectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案配置 的本地化字符串。
        /// </summary>
        public static string SolutionConfiguration {
            get {
                return ResourceManager.GetString("SolutionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端 的本地化字符串。
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总记录数: 的本地化字符串。
        /// </summary>
        public static string TotalRecords {
            get {
                return ResourceManager.GetString("TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入下载链接 的本地化字符串。
        /// </summary>
        public static string UrlRequired {
            get {
                return ResourceManager.GetString("UrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户中心 的本地化字符串。
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 ID 的本地化字符串。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理系统 的本地化字符串。
        /// </summary>
        public static string UserManagementSystem {
            get {
                return ResourceManager.GetString("UserManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎回来 的本地化字符串。
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
    }
}
