using System.Globalization;
using System.Resources;

namespace ColorVision.FloatingBall;

public static class DesktopPetText
{
    private static readonly ResourceManager Manager = new("ColorVision.FloatingBall.DesktopPetResources", typeof(DesktopPetText).Assembly);

    public static string Get(string key) => Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
    public static string Format(string key, params object[] arguments) => string.Format(CultureInfo.CurrentCulture, Get(key), arguments);

    public static string Title => Get("Title");
    public static string ChooseCompanion => Get("ChooseCompanion");
    public static string Subtitle => Get("Subtitle");
    public static string Create => Get("Create");
    public static string Refresh => Get("Refresh");
    public static string Wake => Get("Wake");
    public static string Hide => Get("Hide");
    public static string AvailablePets => Get("AvailablePets");
    public static string Select => Get("Select");
    public static string Selected => Get("Selected");
    public static string Searching => Get("Searching");
    public static string SearchingAll => Get("SearchingAll");
    public static string Loaded => Get("Loaded");
    public static string LoadedWithoutCodex => Get("LoadedWithoutCodex");
    public static string RefreshFailed => Get("RefreshFailed");
    public static string Unavailable => Get("Unavailable");
    public static string CodexOpened => Get("CodexOpened");
    public static string ImportNotFound => Get("ImportNotFound");
    public static string CreatedSelected => Get("CreatedSelected");
    public static string WatchExpired => Get("WatchExpired");
    public static string CodexCreatedSelected => Get("CodexCreatedSelected");
    public static string Preferences => Get("Preferences");
    public static string Appearance => Get("Appearance");
    public static string FollowCopilot => Get("FollowCopilot");
    public static string CopilotNotifications => Get("CopilotNotifications");
    public static string Advanced => Get("Advanced");
    public static string CustomPets => Get("CustomPets");
    public static string CustomSubtitle => Get("CustomSubtitle");
    public static string OpenFolder => Get("OpenFolder");
    public static string SourceColorVisionBuiltIn => Get("SourceColorVisionBuiltIn");
    public static string SourceColorVisionCustom => Get("SourceColorVisionCustom");
    public static string SourceCodexBuiltIn => Get("SourceCodexBuiltIn");
    public static string SourceCodexCustom => Get("SourceCodexCustom");
    public static string XiaocaiName => Get("XiaocaiName");
    public static string XiaocaiDescription => Get("XiaocaiDescription");
    public static string CodexDescription => Get("CodexDescription");
    public static string DeweyDescription => Get("DeweyDescription");
    public static string FireballDescription => Get("FireballDescription");
    public static string HootsDescription => Get("HootsDescription");
    public static string RockyDescription => Get("RockyDescription");
    public static string SeedyDescription => Get("SeedyDescription");
    public static string StackyDescription => Get("StackyDescription");
    public static string BsodDescription => Get("BsodDescription");
    public static string NullSignalDescription => Get("NullSignalDescription");
    public static string DefaultPackageDescription => Get("DefaultPackageDescription");
    public static string CreateTitle => Get("CreateTitle");
    public static string CreateSubtitle => Get("CreateSubtitle");
    public static string CreateWithCodex => Get("CreateWithCodex");
    public static string ImportSpriteSheet => Get("ImportSpriteSheet");
    public static string GenerateWithCodex => Get("GenerateWithCodex");
    public static string CodexGenerationDescription => Get("CodexGenerationDescription");
    public static string CodexStatus => Get("CodexStatus");
    public static string DetectingCodex => Get("DetectingCodex");
    public static string Concept => Get("Concept");
    public static string ConceptHint => Get("ConceptHint");
    public static string NextSteps => Get("NextSteps");
    public static string NextStepsDescription => Get("NextStepsDescription");
    public static string PetName => Get("PetName");
    public static string OptionalDescription => Get("OptionalDescription");
    public static string SpriteSheetFile => Get("SpriteSheetFile");
    public static string Browse => Get("Browse");
    public static string SpriteSheetFormat => Get("SpriteSheetFormat");
    public static string FormatV2 => Get("FormatV2");
    public static string FormatV1 => Get("FormatV1");
    public static string ImportHint => Get("ImportHint");
    public static string Cancel => Get("Cancel");
    public static string Detecting => Get("Detecting");
    public static string CreateInCodex => Get("CreateInCodex");
    public static string ImportAndSelect => Get("ImportAndSelect");
    public static string SelectSpriteSheet => Get("SelectSpriteSheet");
    public static string SpriteSheetFilter => Get("SpriteSheetFilter");
    public static string CodexCheckFailed => Get("CodexCheckFailed");
    public static string PreparingCodex => Get("PreparingCodex");
    public static string CodexOpenFailed => Get("CodexOpenFailed");
    public static string Importing => Get("Importing");
    public static string CodexReady => Get("CodexReady");
    public static string CodexSkillIncomplete => Get("CodexSkillIncomplete");
    public static string CodexNotFound => Get("CodexNotFound");
    public static string CodexDetected => Get("CodexDetected");
    public static string SkillMissingManifest => Get("SkillMissingManifest");
    public static string BundledSkillNotFound => Get("BundledSkillNotFound");
    public static string BundledSkillIncomplete => Get("BundledSkillIncomplete");
    public static string InvalidSkillDirectory => Get("InvalidSkillDirectory");
    public static string SkillCopyIncomplete => Get("SkillCopyIncomplete");
    public static string ConceptTooLong => Get("ConceptTooLong");
    public static string CodexHomeNotFound => Get("CodexHomeNotFound");
    public static string SkillLinkedFile => Get("SkillLinkedFile");
    public static string SkillOutsideDirectory => Get("SkillOutsideDirectory");
    public static string SkillLinkedDirectory => Get("SkillLinkedDirectory");
    public static string NameRequired => Get("NameRequired");
    public static string DescriptionTooLong => Get("DescriptionTooLong");
    public static string InvalidSpriteVersion => Get("InvalidSpriteVersion");
    public static string ChooseSpriteFile => Get("ChooseSpriteFile");
    public static string SpriteFileNotFound => Get("SpriteFileNotFound");
    public static string UnsupportedSpriteFormat => Get("UnsupportedSpriteFormat");
    public static string SpriteTooLarge => Get("SpriteTooLarge");
    public static string SpriteDecodeFailed => Get("SpriteDecodeFailed");
    public static string SpriteGridInvalid => Get("SpriteGridInvalid");
}

