namespace ColorVision.UI.Desktop.Operations
{
    public static class OperationsCapabilityCatalog
    {
        public const string SchemaVersion = "1.8";

        private static readonly IReadOnlyList<OperationsCapabilityDescriptor> Capabilities =
        [
            new()
            {
                Id = "ops.status.read",
                Title = "Read operational status",
                Description = "Read the current ColorVision host, process, window, and LAN endpoint status.",
                Category = "status",
                Provider = "desktop.lan-remote",
                Permission = "ops.status.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                OutputSchema = new { type = "object", additionalProperties = true },
                Evidence = ["host.snapshot"],
                Available = true,
            },
            new()
            {
                Id = "ops.logs.read",
                Title = "Read recent operational logs",
                Description = "Read a bounded and redacted window of recent ColorVision application logs.",
                Category = "diagnostics",
                Provider = "desktop.lan-remote",
                Permission = "ops.logs.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new
                {
                    type = "object",
                    properties = new { count = new { type = "integer", minimum = 1, maximum = 120 } },
                    additionalProperties = false,
                },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.lines"] },
                Evidence = ["application.log"],
                Available = false,
                BlockedReason = "raw_log_surface_not_exposed_to_field_clients",
            },
            new()
            {
                Id = "ops.alerts.read",
                Title = "Read recent operational alerts",
                Description = "Read bounded warning, error, and fatal summaries derived from the latest application log with credential and user-profile redaction.",
                Category = "alerts",
                Provider = "desktop.operations",
                Permission = "ops.alerts.read",
                DiscoverableOn = ["desktop", "android"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.alerts[*].summary"] },
                Evidence = ["application.log.summary"],
                Available = true,
            },
            new()
            {
                Id = "ops.diagnostics.events.read",
                Title = "Read a safe recent event digest",
                Description = "Read bounded severity counts, source categories, and redacted recent warning or error summaries without exposing raw log lines or file metadata.",
                Category = "diagnostics",
                Provider = "desktop.operations",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.recentEvents[*].summary"] },
                Evidence = ["application.log.digest"],
                Available = true,
            },
            new()
            {
                Id = "ops.diagnostics.performance.read",
                Title = "Read a bounded runtime performance snapshot",
                Description = "Sample aggregate ColorVision CPU, memory, managed heap, thread, handle, GC, and main-UI responsiveness counters without returning process identity, paths, command lines, or application data.",
                Category = "diagnostics",
                Provider = "desktop.operations",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                TimeoutMs = 2000,
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["process.aggregate-counters", "desktop.ui-latency"],
                Available = true,
            },
            new()
            {
                Id = "ops.flow.runtime.read",
                Title = "Read aggregate current flow runtime status",
                Description = "Read the current flow lifecycle phase, bounded progress estimate, elapsed time, and last terminal outcome without returning flow, template, batch, node, parameter, result, or inspection identities.",
                Category = "diagnostics",
                Provider = "engine.flow-runtime",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                TimeoutMs = 1500,
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["flow.lifecycle.aggregate", "flow.progress.estimate", "flow.last-outcome"],
                Available = true,
            },
            new()
            {
                Id = "ops.flow.cancel",
                Title = "Cancel the active primary flow",
                Description = "Request cancellation of the currently active primary ColorVision flow through its canonical execution session. The request accepts no flow, template, batch, node, or parameter identity.",
                Category = "flow-control",
                Provider = "engine.flow-runtime",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.jobs.create",
                DiscoverableOn = ["desktop", "android"],
                InputSchema = new { type = "object", additionalProperties = false },
                TimeoutMs = 2000,
                Idempotency = "state-dependent",
                SupportsCancellation = false,
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "paired-device-confirmation",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["flow.cancel.request", "job.audit"],
                Available = true,
            },
            new()
            {
                Id = "ops.monitor.read",
                Title = "Read a bounded live operations snapshot",
                Description = "Read aggregate flow state, process counters, UI responsiveness, normalized message-channel and device-state summaries, and alert counts in one foreground monitoring request without returning identities, raw status, log text, or inspection data.",
                Category = "diagnostics",
                Provider = "desktop.operations",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                TimeoutMs = 2500,
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["flow.lifecycle.aggregate", "process.aggregate-counters", "desktop.ui-latency", "mqtt.connection.normalized", "mqtt.subscription.counts", "device.runtime-state.aggregate", "application.alert.counts"],
                Available = true,
            },
            new()
            {
                Id = "ops.audit.read",
                Title = "Read a bounded operations activity timeline",
                Description = "Read the latest 30 de-identified operations audit summaries without returning actor, device, target, or correlation identifiers.",
                Category = "audit",
                Provider = "desktop.operations",
                Permission = "ops.audit.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["operations.audit.summary"],
                Available = true,
            },
            new()
            {
                Id = "ops.triage.read",
                Title = "Read guided remediation recommendations",
                Description = "Turn bounded desktop, job, service, normalized message-channel and device-state, and redacted event evidence into fixed safe-navigation, audited low-risk, or approval-gated remediation recommendations.",
                Category = "diagnostics",
                Provider = "desktop.operations",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["application.log.digest", "desktop.window.state", "operations.job.state", "service.health.allowlist", "mqtt.connection.normalized", "mqtt.subscription.counts", "device.runtime-state.aggregate"],
                Available = true,
            },
            new()
            {
                Id = "ops.services.health.read",
                Title = "Read allowlisted service health",
                Description = "Read normalized health for the fixed ColorVision Service Host and configured MQTT broker without returning service paths, accounts, or command lines.",
                Category = "diagnostics",
                Provider = "engine.windows-service-health",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["windows.scm.allowlist", "mqtt.endpoint.mode"],
                Available = true,
            },
            new()
            {
                Id = "ops.devices.health.read",
                Title = "Read aggregate inspection-device runtime health",
                Description = "Read normalized ready, busy, transitioning, closed, unavailable, and unknown counts grouped into fixed coarse categories, plus aggregate offline, uninitialized, unauthorized, and unclassified reasons without returning device names, codes, identifiers, addresses, topics, configuration, raw status, or measurement data.",
                Category = "diagnostics",
                Provider = "engine.device-registry",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                TimeoutMs = 1500,
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["device.category.counts", "device.runtime-state.aggregate", "device.unavailability-reason.aggregate"],
                Available = true,
            },
            new()
            {
                Id = "ops.messaging.health.read",
                Title = "Read redacted ColorVision message-channel health",
                Description = "Read normalized client connection state, subscription readiness, counts, and aggregate activity times without returning hosts, ports, endpoints, topics, payloads, identifiers, configuration, credentials, certificates, or raw logs.",
                Category = "diagnostics",
                Provider = "engine.mqtt-runtime",
                Permission = "ops.diagnostics.read",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new { type = "object", additionalProperties = false },
                OutputSchema = new { type = "object", additionalProperties = true },
                TimeoutMs = 1000,
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["mqtt.connection.normalized", "mqtt.subscription.counts", "mqtt.activity.aggregate"],
                Available = true,
            },
            new()
            {
                Id = "ops.window.show",
                Title = "Show the ColorVision main window",
                Description = "Bring the existing ColorVision main window to the foreground.",
                Category = "desktop-control",
                Provider = "desktop.window",
                RiskLevel = OperationsRiskLevels.LowRisk,
                Permission = "ops.window.control",
                DiscoverableOn = ["desktop", "android", "copilot"],
                Idempotency = "safe",
                Available = true,
            },
            new()
            {
                Id = "ops.jobs.manage",
                Title = "Submit and review bounded operations jobs",
                Description = "Create bounded operational intents and review their approval state without directly executing privileged commands.",
                Category = "jobs",
                Provider = "desktop.operations",
                RiskLevel = OperationsRiskLevels.LowRisk,
                Permission = "ops.jobs.create",
                DiscoverableOn = ["desktop", "android", "copilot"],
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["job.audit"],
                Available = true,
            },
            new()
            {
                Id = "ops.approvals.decide",
                Title = "Record an operations approval decision",
                Description = "Record a mobile approval or rejection. Capabilities marked for local co-sign remain blocked until that separate desktop decision exists.",
                Category = "approvals",
                Provider = "desktop.operations",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.approvals.decide",
                DiscoverableOn = ["desktop", "android"],
                Approval = new OperationsApprovalPolicy { Mode = "paired-device-confirmation", TtlSeconds = 300, SingleUse = true },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["approval.decision"],
                Available = true,
            },
            new()
            {
                Id = "ops.deployment.receipt.create",
                Title = "Confirm deployment outcome",
                Description = "Submit an installation or verification receipt. This does not initiate deployment.",
                Category = "deployment",
                Provider = "desktop.operations",
                RiskLevel = OperationsRiskLevels.LowRisk,
                Permission = "ops.deployments.receipt.create",
                DiscoverableOn = ["desktop", "android"],
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["deployment.receipt"],
                Available = true,
            },
            new()
            {
                Id = "ops.support.session.request",
                Title = "Request a bounded support session",
                Description = "Request diagnostics or guided support for at most 30 minutes. Local desktop consent is always required.",
                Category = "support",
                Provider = "desktop.operations",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.support.request",
                DiscoverableOn = ["desktop", "android"],
                Approval = new OperationsApprovalPolicy { Mode = "local-co-sign", TtlSeconds = 1800, SingleUse = true, RequiresLocalCoSign = true },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["support.session.audit"],
                Available = true,
            },
            new()
            {
                Id = "ops.support.message.exchange",
                Title = "Exchange a bounded guided-support message",
                Description = "Exchange short text only while the current device's locally approved support session is active.",
                Category = "support",
                Provider = "desktop.operations",
                RiskLevel = OperationsRiskLevels.LowRisk,
                Permission = "ops.support.request",
                DiscoverableOn = ["desktop", "android"],
                InputSchema = new
                {
                    type = "object",
                    properties = new { text = new { type = "string", maxLength = 500 } },
                    required = new[] { "text" },
                    additionalProperties = false,
                },
                Approval = new OperationsApprovalPolicy { Mode = "active-support-session", TtlSeconds = 1800 },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.text"] },
                Evidence = ["support.message.audit"],
                Available = true,
            },
            new()
            {
                Id = "ops.window.minimize",
                Title = "Minimize the ColorVision main window",
                Description = "Minimize the existing ColorVision main window.",
                Category = "desktop-control",
                Provider = "desktop.window",
                RiskLevel = OperationsRiskLevels.LowRisk,
                Permission = "ops.window.control",
                DiscoverableOn = ["desktop", "android", "copilot"],
                Idempotency = "safe",
                Available = true,
            },
            new()
            {
                Id = "ops.window.snapshot.capture",
                Title = "Capture the ColorVision main window",
                Description = "Capture one bounded JPEG of the ColorVision main window only after explicit confirmation on the paired phone. The requesting device has five minutes to read it once.",
                Category = "diagnostics",
                Provider = "desktop.window",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.window.snapshot.create",
                DiscoverableOn = ["desktop", "android"],
                TimeoutMs = 30000,
                Idempotency = "keyed",
                SupportsCancellation = false,
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "paired-device-confirmation",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.window.content"] },
                Evidence = ["window.snapshot.jpeg"],
                Available = true,
            },
            new()
            {
                Id = "ops.window.snapshot.download",
                Title = "Read a one-time ColorVision window snapshot",
                Description = "Read the bounded JPEG produced by a completed snapshot job owned by the requesting device. A successful read consumes the evidence.",
                Category = "diagnostics",
                Provider = "desktop.window",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.window.snapshot.read",
                DiscoverableOn = ["android"],
                TimeoutMs = 30000,
                Idempotency = "single-use",
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "completed-device-owned-job",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["window.snapshot.sha256"],
                Available = true,
            },
            new()
            {
                Id = "ops.diagnostics.bundle.create",
                Title = "Create a diagnostic bundle",
                Description = "Create a bounded, redacted diagnostic evidence bundle after explicit confirmation on the paired phone. A completed bundle remains downloadable only by its requesting device for 24 hours.",
                Category = "diagnostics",
                Provider = "desktop.diagnostics",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.diagnostics.bundle.create",
                DiscoverableOn = ["desktop", "android", "copilot"],
                TimeoutMs = 60000,
                Idempotency = "keyed",
                SupportsCancellation = false,
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "paired-device-confirmation",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true, Redact = ["$.bundle.contents"] },
                Evidence = ["diagnostic.bundle"],
                Available = true,
            },
            new()
            {
                Id = "ops.diagnostics.bundle.download",
                Title = "Download a completed diagnostic bundle",
                Description = "Download the bounded redacted ZIP produced by a completed diagnostic job owned by the requesting device.",
                Category = "diagnostics",
                Provider = "desktop.diagnostics",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.diagnostics.bundle.read",
                DiscoverableOn = ["android"],
                TimeoutMs = 30000,
                Idempotency = "safe",
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "completed-device-owned-job",
                    TtlSeconds = 86400,
                    SingleUse = false,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true },
                Evidence = ["diagnostic.bundle.sha256"],
                Available = true,
            },
            new()
            {
                Id = "ops.application.restart",
                Title = "Restart the current ColorVision application",
                Description = "Cleanly restart only the current ColorVision application after explicit confirmation on the paired phone. Active inspection execution blocks the restart, and no executable path or arguments are accepted.",
                Category = "maintenance",
                Provider = "desktop.application",
                RiskLevel = OperationsRiskLevels.ApprovalRequired,
                Permission = "ops.jobs.create",
                DiscoverableOn = ["desktop", "android"],
                InputSchema = new { type = "object", additionalProperties = false },
                TimeoutMs = 90000,
                Idempotency = "keyed",
                SupportsCancellation = false,
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "paired-device-confirmation",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Audit = new OperationsAuditPolicy { Required = true },
                Execution = new OperationsExecutionPolicy
                {
                    Target = "desktop-application",
                    BrokerCapability = "application.restart.current",
                },
                Evidence = ["application.restart.handoff", "application.restart.reconnected"],
                Available = true,
            },
            new()
            {
                Id = "ops.service.restart",
                Title = "Restart the fixed MQTT Windows service",
                Description = "Restart only the fixed Mosquitto service through ColorVisionServiceHost after explicit confirmation on the paired phone.",
                Category = "maintenance",
                Provider = "desktop.privileged-broker",
                RiskLevel = OperationsRiskLevels.Privileged,
                Permission = "ops.service.restart",
                DiscoverableOn = ["desktop", "android", "copilot"],
                InputSchema = new
                {
                    type = "object",
                    properties = new
                    {
                        serviceId = new { type = "string", @enum = new[] { "mosquitto" } },
                    },
                    required = new[] { "serviceId" },
                    additionalProperties = false,
                },
                TimeoutMs = 60000,
                Idempotency = "keyed",
                SupportsCancellation = false,
                Approval = new OperationsApprovalPolicy
                {
                    Mode = "paired-device-confirmation",
                    TtlSeconds = 300,
                    SingleUse = true,
                    RequiresLocalCoSign = false,
                },
                Execution = new OperationsExecutionPolicy
                {
                    Target = "service-host",
                    BrokerCapability = "service.restart.known",
                },
                RollbackCapability = "ops.service.start",
                Evidence = ["service.before", "service.after"],
                Available = true,
            },
        ];

        public static IReadOnlyList<OperationsCapabilityDescriptor> GetAll() => Capabilities;
    }
}
