name: Auto PR from develop to master

on:
  # schedule:
    # - cron: '0 0 * * 1' # 每周一的 0:00 执行一次
  push:
    branches:
      - develop

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: develop
          title: 'Auto PR: Sync develop to master'
          body: |
            This pull request was automatically created by a GitHub Action to sync changes from develop to master.